// Contenido de cada página de solución.
// Fuente: sitio oficial de cada producto, consultado en octubre de 2026 (ver _build/investigacion/).
// Regla: no se publican precios ni cifras que no aparezcan en el sitio oficial.

export const CONTENIDO = {
  unticloud: {
    titulo: 'UntiCloud: horarios y ausentismo docente desde Untis · Grupo Logic',
    descripcion: 'UntiCloud lleva Untis a la web: horarios en tiempo real, guardias, reemplazos e indicadores de ausentismo docente para rectoría y coordinación.',
    h1: 'UntiCloud: horarios, guardias y ausentismo docente de Untis, en la web',
    altPortada: 'Página de inicio de UntiCloud con el panel de administración de horarios, guardias y estadísticas',
    reto: [
      'Muchos colegios planifican sus horarios con Untis, pero la información queda encerrada en el equipo de escritorio de la coordinación. Los docentes dependen de horarios impresos, las sustituciones se coordinan por teléfono y rectoría no tiene a la mano un dato tan básico como el índice de ausentismo docente del mes.',
      'Calcular ese índice, verificar las horas de cada materia del programa IB o preparar el informe para la junta suele significar horas de trabajo manual en hojas de cálculo, con el riesgo de errores que eso implica.',
      'UntiCloud resuelve el problema sin cambiar la forma en que su institución planifica: toma los mismos archivos que Untis Desktop ya exporta y los publica en un panel web para toda la comunidad, con la información que cada rol necesita.',
    ],
    funciones: [
      ['calendario', 'Horarios en tiempo real', 'Vistas por docente, por curso y en agenda semanal, actualizadas al instante y disponibles en cualquier dispositivo.'],
      ['grafica', 'Estadísticas de ausentismo', 'Índice de ausentismo docente por mes, motivo y curso, con filtro por sección. Se calcula solo sobre las horas que el docente debía impartir.'],
      ['escudo', 'Guardias de recreo', 'Cada docente ve qué día y en qué zona le corresponde vigilar. La asignación llega directamente desde Untis, sin papeles.'],
      ['reemplazo', 'Reemplazos y planificación', 'Sustituciones del día con PDF imprimible, disponibilidad docente para planificar ausencias e histórico por motivo.'],
      ['birrete', 'Indicadores IB', 'Cumplimiento de horas HL y SL frente a los mínimos del programa, seguimiento del núcleo EE·TdC·CAS y horas perdidas en la sección IB.'],
      ['comparar', 'Comparador y carga horaria', 'Compare en paralelo hasta 4 docentes o cursos y consulte la carga semanal de cada docente: lecciones, grupos, materias y salones.'],
    ],
    galeria: [
      ['unticloud-ib', 'Tabla de indicadores IB de UntiCloud con proyección de horas por materia frente al mínimo HL y SL', 'Indicadores IB', 'Semáforo de cumplimiento por materia y estado del núcleo IB, calculado a partir del horario de Untis.'],
      ['unticloud-ausentismo', 'Gráfica de UntiCloud con el índice de ausentismo docente por mes del año lectivo', 'Ausentismo por mes', 'Índice mensual con umbrales de atención, para que rectoría vea la tendencia del año lectivo de un vistazo.'],
    ],
    extra: {
      titulo: 'Integración directa con Untis',
      items: [
        'Compatible con Untis 2020 o superior.',
        'Lee los archivos GPU que Untis Desktop ya genera para respaldo.',
        'Importación con un clic, sin duplicados y con historial de auditoría.',
        'Las secciones (IB, bachillerato, primaria…) se leen de Untis automáticamente.',
        'Usuarios y roles: rector, coordinadores y docentes ven solo lo que necesitan.',
        '100 % web: sin instalación ni servidores propios.',
      ],
    },
    publico: [
      ['institucion', 'Rectoría', 'Vista estratégica para decidir con datos.', ['Índice de ausentismo por período', 'Tendencias mes a mes', 'Horas sin cubrir con alerta visual']],
      ['ajustes', 'Coordinación TIC', 'Integración limpia con Untis, sin API complejas.', ['Importación idempotente de archivos', 'Historial de importaciones con errores', 'Gestión de usuarios y permisos']],
      ['birrete', 'Coordinación académica e IB', 'Planificación y supervisión en un solo lugar.', ['Reemplazos del día y ausencias', 'Carga horaria por docente y curso', 'Semáforo HL/SL y núcleo IB']],
      ['usuarios', 'Docentes', 'Consulta rápida desde el celular.', ['Horario personal completo', 'Vigilancias y zonas asignadas', 'Sustituciones que le corresponden']],
    ],
    implementacion: [
      ['Exportar desde Untis', 'Su equipo genera en Untis Desktop los archivos GPU de siempre. No cambia nada en su flujo de planificación.'],
      ['Importar al panel', 'La coordinación TIC sube los archivos y los importa con un clic. Según el fabricante, la importación toma menos de 5 minutos.'],
      ['Configurar roles', 'Definimos con su equipo qué ve cada perfil: rectoría, coordinaciones y docentes.'],
      ['Abrir a la institución', 'Docentes y directivos acceden desde cualquier dispositivo. El fabricante describe la puesta en marcha como el trabajo de una tarde.'],
    ],
    licencias: {
      intro: 'UntiCloud se licencia por año, con facturación anual, en tres modalidades según el tamaño y la estructura de su institución.',
      modalidades: [
        ['Institución', 'Para un solo centro educativo de hasta 150 docentes.', ['Horarios de docentes y cursos en tiempo real', 'Guardias y recreos', 'Estadísticas de ausentismo mensual', 'Sustituciones del día', 'Usuarios y roles']],
        ['Profesional', 'Para colegios que quieren análisis avanzado y programa IB.', ['Todo lo del plan Institución', 'Módulo Indicadores IB', 'Filtro por sección en estadísticas', 'Planificación y carga horaria', 'Comparador de 4 horarios', 'Exportación PDF e informes para junta']],
        ['Red de Colegios', 'Para redes con varias sedes que necesitan un panel unificado.', ['Todo lo del plan Profesional', 'Varias sedes en un panel', 'Estadísticas comparativas por sede', 'Acceso multi-institución por usuario', 'Nivel de servicio por contrato']],
      ],
    },
    preguntas: [
      ['¿Tenemos que cambiar nuestra forma de planificar en Untis?', 'No. UntiCloud trabaja con los archivos GPU que Untis Desktop ya exporta. Su equipo sigue planificando exactamente igual.'],
      ['¿Qué versión de Untis necesitamos?', 'El fabricante indica compatibilidad con Untis 2020 o superior.'],
      ['¿Hay que instalar algo en los equipos del colegio?', 'No. UntiCloud funciona 100 % en la web, sin instalación ni servidores propios.'],
      ['¿El módulo de Indicadores IB está en todos los planes?', 'No. Indicadores IB se incluye en los planes Profesional y Red de Colegios. En la propuesta le indicamos qué modalidad corresponde a su institución.'],
      ['¿Cada usuario ve toda la información?', 'No. Cada rol ve solo lo que necesita: rectoría ve la información global, las coordinaciones sus herramientas de gestión y cada docente su propio horario y sus guardias.'],
    ],
    relacionadas: ['veyon-control', 'edunova', 'vcodepro'],
    ld: { applicationSubCategory: 'Gestión escolar y horarios', operatingSystem: 'Web' },
  },

  'veyon-control': {
    titulo: 'Veyon Control: gestión de aulas de informática · Grupo Logic',
    descripcion: 'Veyon Control permite supervisar, guiar y controlar cada equipo del aula de informática desde un panel, con licencia anual, actualizaciones y soporte.',
    h1: 'Veyon Control: supervisión y control de aulas de informática',
    altPortada: 'Página de inicio de Veyon Control con el panel que muestra las pantallas de los equipos del aula',
    reto: [
      'En una sala de informática el docente no ve qué hay en cada pantalla. Mantener al grupo enfocado, resolver dudas puesto por puesto y repartir material con memorias USB consume buena parte de la clase.',
      'Para el área de TI el reto es otro: mantener al día el software de decenas de equipos, en varias salas y con distintos sistemas operativos, sin depender de servicios externos.',
      'Veyon resuelve las dos cosas: el docente dirige la clase desde un panel con todas las pantallas en vivo, y Veyon Control mantiene cada puesto en la versión vigente, capacita al profesorado y da soporte durante todo el año.',
    ],
    nota: '<strong>Veyon y Veyon Control.</strong> Veyon es un software de gestión de aulas desarrollado en Alemania. Veyon Control ofrece su licenciamiento anual, las actualizaciones en cada puesto, la capacitación docente y el soporte.',
    funciones: [
      ['ojo', 'Supervisión en vivo', 'Miniaturas en tiempo real de todos los puestos, ordenadas según la distribución real del aula, con vista ampliada de cualquier equipo.'],
      ['soporte', 'Control remoto', 'El docente toma el teclado y el ratón de un equipo para resolver dudas sin levantarse, o accede en modo de solo observación.'],
      ['presentacion', 'Demostración', 'Emite su pantalla, o la de un estudiante, a toda la clase: a pantalla completa o en ventana para practicar mientras se observa.'],
      ['candado', 'Bloqueo y atención', 'Congela pantallas, teclados y ratones con un clic. También enciende por red, cierra sesiones, reinicia y apaga el grupo.'],
      ['exportar', 'Envío de archivos', 'Reparte enunciados y plantillas a todos los puestos a la vez, con apertura automática si se desea. Sin memorias USB.'],
      ['usuarios', 'Integración con su directorio', 'Lee aulas, equipos y grupos desde LDAP o Active Directory, y desde Microsoft Entra ID mediante complemento.'],
    ],
    galeria: [
      ['veyon-control-aula', 'Veyon Master con la lista de aulas y equipos, las pantallas en miniatura y el menú de acciones sobre un equipo', 'Veyon Master', 'El panel del docente: lista de aulas, pantallas en vivo y acciones como demostración, bloqueo o control remoto.'],
    ],
    extra: {
      titulo: 'Seguridad y despliegue',
      items: [
        'Comunicación cifrada con TLS y claves propias por institución.',
        'Funciona en la red local, sin servidor externo ni cuentas en la nube.',
        'Windows (32 y 64 bits) y Linux: Debian, Ubuntu, Fedora, openSUSE, RHEL y Rocky Linux.',
        'Instalación silenciosa y configuración por línea de comandos.',
        'Interfaz disponible en más de 30 idiomas.',
        'Complementos opcionales: control de internet, grabación de pantalla, chat, audio y USB.',
      ],
    },
    publico: [
      ['ajustes', 'Coordinación TIC', 'Un sistema que se mantiene al día.', ['Actualizaciones en todos los puestos', 'Despliegue silencioso o por imagen', 'Integración con LDAP o Active Directory']],
      ['usuarios', 'Docentes de informática', 'La clase, bajo control.', ['Pantallas del grupo en vivo', 'Demostraciones a pantalla completa', 'Bloqueo para recuperar la atención']],
      ['rubrica', 'Coordinación académica', 'Evaluaciones más ordenadas.', ['Reparto simultáneo del enunciado', 'Bloqueo de equipos al terminar', 'Restricción de internet y USB con complementos']],
      ['institucion', 'Rectoría', 'Salas de informática bien aprovechadas.', ['Licencia anual según el número de equipos', 'Capacitación incluida en cada plan', 'Soporte durante toda la vigencia']],
    ],
    implementacion: [
      ['Levantamiento', 'Se revisa cuántos equipos hay, qué sistemas operativos usan y cómo está la red. De ahí salen el plan y el cronograma.'],
      ['Licencia y actualización', 'Se activa la licencia y todos los puestos quedan en la versión vigente, con paquetes listos para las próximas actualizaciones.'],
      ['Capacitación', 'Formación del profesorado en el uso diario y del área de TI en la administración, con material que queda en la institución.'],
      ['Soporte y actualizaciones', 'Durante la vigencia se atienden incidencias, se publica cada nueva versión en los equipos y se revisa que todo esté al día.'],
    ],
    licencias: {
      intro: 'Cada plan incluye la licencia anual, las actualizaciones de versión en todos los puestos, la capacitación del profesorado y doce meses de soporte. Se elige según el número de equipos.',
      modalidades: [
        ['Licencia Aula', 'Para un aula única o una sala de cómputo pequeña.', ['Hasta 10 equipos', '1 panel docente (Veyon Master)', 'Actualizaciones en todos los puestos', 'Capacitación inicial de 2 horas', 'Soporte por correo durante 12 meses']],
        ['Licencia Laboratorio', 'Para varias salas o un laboratorio grande.', ['Hasta 50 equipos', 'Hasta 3 paneles docentes', 'Integración con LDAP o Active Directory', 'Paquetes de actualización listos para distribuir', 'Capacitación de 4 horas y soporte prioritario']],
        ['Licencia Campus', 'Para sedes con varias aulas y equipo de TI propio.', ['Hasta 100 equipos', 'Paneles docentes sin límite', 'Actualizaciones coordinadas por aula', 'Capacitación por sedes', 'Revisión semestral del estado de actualización']],
        ['Licencia de Sitio', 'Cobertura total de una sede, sin contar puestos.', ['Equipos ilimitados en la sede', 'Integración con Microsoft Entra ID', 'Paquetes para imagen del sistema o GPO', 'Capacitación sin límite durante el año', 'Soporte dedicado con tiempos acordados']],
      ],
      pie: 'Para varias sedes se prepara una propuesta a la medida.',
    },
    preguntas: [
      ['¿Necesita conexión a internet o una cuenta en la nube?', 'No. Todo funciona dentro de la red local de la institución: el panel del docente se comunica directamente con cada equipo, sin servidor externo obligatorio ni registro de cuentas.'],
      ['¿Qué sistemas operativos admite?', 'Windows (32 y 64 bits) y las principales distribuciones Linux: Debian, Ubuntu, Fedora, openSUSE, RHEL y Rocky Linux. Equipos Windows y Linux pueden convivir en la misma aula y verse en el mismo panel.'],
      ['¿Cómo se protege el acceso a los equipos?', 'La comunicación va cifrada con TLS. El acceso se autoriza con una clave criptográfica propia de la institución o con credenciales de usuario validadas contra el sistema o el directorio, restringidas a un grupo.'],
      ['¿Sirve para exámenes?', 'Sí. Permite repartir el enunciado a todos los equipos a la vez y bloquearlos al terminar. Con complementos también se puede restringir el acceso a internet y a los puertos USB.'],
      ['¿Qué pasa si el colegio tiene más equipos que los del plan?', 'Se pasa al plan siguiente. Según el fabricante, solo se cobra la diferencia proporcional al tiempo restante de vigencia; con varias sedes o bastante más de 100 equipos, la Licencia de Sitio suele resultar más conveniente.'],
    ],
    relacionadas: ['unticloud', 'vcodepro', 'codexia'],
    ld: { applicationSubCategory: 'Gestión de aulas de informática', operatingSystem: 'Windows, Linux', softwareVersion: '4.11.2' },
  },

  'aulamagica-ia': {
    titulo: 'AulaMágica IA: inteligencia artificial segura para colegios',
    descripcion: 'AulaMágica IA reúne más de 80 herramientas de IA para docentes y más de 50 para estudiantes, con control institucional de usuarios, políticas y uso.',
    h1: 'AulaMágica IA: inteligencia artificial segura para toda su institución',
    altPortada: 'Página de inicio de AulaMágica IA con su buscador de herramientas de inteligencia artificial para docentes',
    reto: [
      'Los docentes ya usan inteligencia artificial, muchas veces con cuentas personales y sin criterios comunes. La institución no sabe qué información se comparte, qué herramientas usan los estudiantes ni cómo se protege a los menores.',
      'Al mismo tiempo, el equipo docente dedica horas cada semana a planear, preparar evaluaciones, redactar observaciones de boletín y adaptar materiales para estudiantes con necesidades diversas.',
      'AulaMágica IA ordena ese uso bajo el control de la institución: una plataforma con herramientas pensadas para el aula, administración centralizada de usuarios y políticas de uso responsable que define su colegio.',
    ],
    nota: '<strong>¿AulaMágica IA o EduNova?</strong> AulaMágica IA es una caja de herramientas de inteligencia artificial para el trabajo del docente y del estudiante. Si busca un sistema que conecte todo el ciclo de aprendizaje —libro de texto, clases, evaluación, recuperación y boletín—, conozca <a href="/soluciones/edunova/">EduNova</a>. Le ayudamos a elegir según el momento de su institución.',
    funciones: [
      ['lapiz', 'Planeación de clases', 'Planes de clase alineados a estándares y DBA, presentaciones a partir de un tema o un texto, guías por pasos e ideas para actividades.'],
      ['rubrica', 'Evaluación', 'Quices de selección múltiple con clave de respuestas, rúbricas con niveles de desempeño y retroalimentación específica de los escritos.'],
      ['accesibilidad', 'Inclusión', 'Reescritor de textos por nivel de complejidad y apoyo para construir planes de ajustes razonables (PIAR) que el equipo revisa y aprueba.'],
      ['robot', 'Tutor para estudiantes', 'Un tutor de IA que guía sin dar la respuesta, dentro de actividades creadas y supervisadas por el docente.'],
      ['institucion', 'Administración institucional', 'Usuarios y licencias centralizados, paneles de uso y adopción por sede y políticas de uso responsable configurables.'],
      ['mensaje', 'Comunicación', 'Observaciones de boletín claras y respetuosas, y correos profesionales a familias y colegas con el tono adecuado.'],
    ],
    galeria: [],
    extra: {
      titulo: 'Seguridad e integraciones',
      items: [
        'Cifrado de la información en tránsito y en reposo.',
        'Control de acceso por roles e inicio de sesión con cuentas institucionales.',
        'Moderación de contenido y alertas para temas sensibles.',
        'Supervisión docente de las interacciones de los estudiantes.',
        'Declara cumplir el RGPD y no usar los datos para entrenar modelos de IA.',
        'Integración con Google Workspace, Microsoft 365, Canvas, Moodle, Classroom y Teams.',
      ],
    },
    publico: [
      ['institucion', 'Rectoría', 'Visibilidad y control sobre el uso de la IA.', ['Paneles de uso y adopción por sede', 'Herramientas disponibles por perfil', 'Políticas de uso responsable']],
      ['ajustes', 'Coordinación TIC', 'Administración sin complicaciones.', ['Inicio de sesión institucional', 'Integración con Google y Microsoft', 'Alta de usuarios uno a uno o masiva']],
      ['birrete', 'Coordinación académica', 'Coherencia pedagógica en toda la institución.', ['Planes alineados a estándares y DBA', 'Observaciones con tono institucional', 'Apoyo a ajustes razonables']],
      ['usuarios', 'Docentes', 'Más tiempo para enseñar.', ['Más de 80 herramientas', 'Exportación a documentos y presentaciones', 'Formación y certificación']],
    ],
    implementacion: [
      ['Elegir la licencia', 'Definimos con usted la modalidad según el número de docentes, directivos y sedes.'],
      ['Activar y configurar', 'Se activa la licencia y se configuran las políticas de uso y las herramientas disponibles para cada perfil.'],
      ['Invitar al equipo', 'Los docentes se agregan uno a uno o de forma masiva desde el portal de la institución.'],
      ['Formar y acompañar', 'Capacitación de arranque, talleres en vivo y cursos de certificación para que cada docente use la IA con criterio.'],
    ],
    licencias: {
      intro: 'AulaMágica IA se licencia por institución con vigencia de 12 meses. Ambas modalidades incluyen formación.',
      modalidades: [
        ['Licencia Escuela', 'Para una institución educativa con una o varias jornadas.', ['Hasta 10 usuarios (docentes y directivos)', 'Más de 80 herramientas para docentes', 'Más de 50 herramientas para estudiantes', 'Panel de administración', 'Capacitación virtual de arranque', 'Soporte por correo y chat']],
        ['Licencia por Volumen', 'Para redes de colegios, varias sedes y secretarías.', ['Hasta 250 usuarios en varias sedes', 'Todo lo de la Licencia Escuela', 'Herramientas personalizadas para su red', 'Reportes de uso e impacto por sede', 'Plan de formación docente', 'Gerente de cuenta y soporte prioritario']],
      ],
      pie: '¿Su institución necesita más de 250 usuarios? Preparamos una propuesta a la medida.',
    },
    preguntas: [
      ['¿Los datos de docentes y estudiantes se usan para entrenar modelos de IA?', 'El fabricante declara que no usa los datos de docentes ni estudiantes para entrenar modelos de IA, que no vende información y que trata los datos conforme al RGPD europeo y a la ley española de protección de datos.'],
      ['¿Es seguro que los estudiantes usen la plataforma?', 'Los estudiantes trabajan en actividades creadas y supervisadas por el docente, con filtros de contenido adecuados a la edad, alertas para temas sensibles e historial visible para el docente en todo momento.'],
      ['¿Se integra con Google Workspace o Microsoft 365?', 'Sí. El fabricante indica integración e inicio de sesión con Google Workspace, Microsoft 365, Canvas, Moodle, Classroom y Teams.'],
      ['¿Podemos cambiar los usuarios durante la vigencia?', 'Sí. Desde el portal se pueden agregar, retirar o reemplazar usuarios en cualquier momento, dentro del número de cupos de la licencia.'],
      ['¿En qué se diferencia de EduNova?', 'AulaMágica IA es un conjunto de herramientas de IA para el trabajo diario del docente y del estudiante. EduNova es un sistema integrado que conecta libro de texto, clases, evaluación, recuperación y comunicación con familias. Le ayudamos a elegir según sus prioridades.'],
    ],
    relacionadas: ['edunova', 'bookstudio', 'vcodepro'],
    ld: { applicationSubCategory: 'Inteligencia artificial para la enseñanza', operatingSystem: 'Web' },
  },

  edunova: {
    titulo: 'EduNova: sistema de aprendizaje con IA para su colegio',
    descripcion: 'EduNova conecta en 8 módulos con IA todo el ciclo de aprendizaje, del libro de texto al boletín, para docentes, directivos, estudiantes y familias.',
    h1: 'EduNova: sistema de aprendizaje con IA para todo su colegio',
    altPortada: 'Página de inicio de EduNova con el módulo de planeación de clases con inteligencia artificial',
    reto: [
      'En muchos colegios, la planeación vive en un documento, las evaluaciones en otra plataforma, las notas en el sistema académico y la comunicación con las familias en grupos de mensajería. El trabajo se duplica y nadie tiene una visión completa del aprendizaje.',
      'Los directivos necesitan saber a tiempo qué grados, áreas o sedes requieren apoyo; los docentes, recuperar horas de planeación y corrección; y las familias, entender con claridad cómo avanzan sus hijos. El fabricante estima una reducción de hasta el 70 % del tiempo de planeación y corrección.',
      'EduNova reúne todo el ciclo en un solo sistema con inteligencia artificial: cada módulo alimenta al siguiente, desde el libro de texto hasta el boletín, y cada perfil de la comunidad educativa tiene su propio espacio.',
    ],
    nota: '<strong>¿EduNova o AulaMágica IA?</strong> EduNova es un sistema integrado para todo el ciclo de aprendizaje de la institución. Si lo que busca es un conjunto de herramientas de IA para el trabajo diario del docente, conozca <a href="/soluciones/aulamagica-ia/">AulaMágica IA</a>. Le ayudamos a elegir según el momento de su institución.',
    funcionesTitulo: 'Ocho módulos conectados',
    funciones: [
      ['libro', '01 · Libros de texto', 'Contenidos por área, grado y periodo, alineados con los estándares básicos de competencias y los DBA, en versión impresa, digital o mixta.'],
      ['lapiz', '02 · Planeación', 'La IA propone objetivos, momentos de la clase, actividades y recursos. Todo es editable y se exporta a Word o PDF con el formato de su institución.'],
      ['presentacion', '03 · Clases', 'Presentaciones generadas desde la planeación, preguntas en vivo y tableros de participación. Funciona con conexión limitada.'],
      ['accesibilidad', '04 · Accesibilidad', 'Versión de lectura fácil, apoyos visuales, audio narrado y sugerencias de ajustes razonables según el PIAR.'],
      ['rubrica', '05 · Evaluaciones', 'Quices, talleres y simulacros con estructura de prueba de Estado, bancos de preguntas por competencia y rúbricas para preguntas abiertas.'],
      ['check', '06 · Calificación', 'Corrección asistida de respuestas abiertas y manuscritas, con retroalimentación personalizada que el docente revisa y aprueba.'],
      ['reemplazo', '07 · Recuperación', 'Diagnóstico por competencia y actividades de nivelación a la medida de cada estudiante, con seguimiento del avance.'],
      ['familia', '08 · Comunicación', 'Boletines comprensibles, circulares programadas y resúmenes semanales para las familias.'],
    ],
    galeria: [
      ['edunova-libros', 'Biblioteca de EduNova con guías de Matemáticas, Ciencias Naturales, Lenguaje y Ciencias Sociales para grado quinto', 'Libros de texto', 'Guías organizadas por área, grado y unidad, alineadas a los DBA.'],
    ],
    extra: {
      titulo: 'EduNova Studio: los libros de su institución',
      items: [
        'Textos escolares propios con su modelo pedagógico y su PEI.',
        'Portadas, colores y logotipo de la institución.',
        'Formato impreso, digital o combinado.',
        'Contenido actualizable cada año sin reimprimir todo.',
        'Incluido en la Licencia por Volumen.',
        'Una alternativa a los textos comerciales para sus estudiantes.',
      ],
    },
    publico: [
      ['institucion', 'Directivos', 'Visibilidad real del aprendizaje.', ['Indicadores por grado, área y sede', 'Alertas tempranas de bajo desempeño', 'Menos costo en materiales impresos']],
      ['lapiz', 'Docentes', 'Menos tareas repetitivas.', ['Planeaciones y guías con IA', 'Evaluaciones y rúbricas en segundos', 'Corrección asistida con retroalimentación']],
      ['birrete', 'Estudiantes', 'Un tutor que se adapta a su ritmo.', ['Tutor con IA que explica paso a paso', 'Retos y progreso visible', 'Práctica personalizada de refuerzo']],
      ['familia', 'Familias', 'Acompañar sin complicaciones.', ['Boletines claros', 'Avisos y circulares en el celular', 'Recomendaciones para apoyar en casa']],
    ],
    implementacion: [
      ['Elegir la licencia', 'Escuela para una institución con una sede, o Volumen para varias sedes o redes de colegios.'],
      ['Activar la institución', 'Se activa la licencia y se habilita el portal de clientes con el código, la vigencia y los cupos.'],
      ['Registrar al equipo', 'Desde el portal se registran docentes y directivos, también por carga masiva.'],
      ['Formar al equipo', 'Capacitación inicial en línea y, en la Licencia por Volumen, capacitación presencial o virtual por sede.'],
    ],
    licencias: {
      intro: 'EduNova se licencia por año, con todas las herramientas, actualizaciones y soporte incluidos durante la vigencia.',
      modalidades: [
        ['Licencia Escuela', 'Para una institución educativa con una sede.', ['Planeación de clases y guías con IA', 'Generador de evaluaciones y rúbricas', 'Corrección asistida y reportes', 'Materiales accesibles e inclusivos', 'Capacitación inicial en línea', 'Soporte por correo y WhatsApp']],
        ['Licencia por Volumen', 'Para redes de colegios, secretarías y grupos con varias sedes.', ['Hasta 250 usuarios y hasta 5 sedes', 'Todo lo de la Licencia Escuela', 'Panel de indicadores para directivos', 'Studio: libros personalizados', 'Plan de recuperación por estudiante', 'Gerente de cuenta y soporte prioritario']],
      ],
    },
    preguntas: [
      ['¿Hay que instalar algo?', 'No. EduNova funciona desde el navegador en computadores, tabletas y celulares; solo se necesita conexión a internet.'],
      ['¿Qué es EduNova Studio?', 'Es el servicio para crear textos escolares propios, con el modelo pedagógico, la identidad y el contexto de su institución, en formato impreso, digital o mixto. Está incluido en la Licencia por Volumen.'],
      ['¿Incluye preparación para pruebas de Estado?', 'Sí. El módulo de Evaluaciones permite crear simulacros con estructura de prueba de Estado, con bancos de preguntas por competencia y distintos niveles de dificultad.'],
      ['¿Cómo se tratan los datos de los estudiantes?', 'El fabricante indica que trata los datos conforme a la Ley 1581 de 2012 y que la institución es dueña de su información: puede solicitar su exportación o eliminación.'],
      ['¿En qué se diferencia de AulaMágica IA?', 'EduNova integra el ciclo completo de aprendizaje en ocho módulos conectados. AulaMágica IA es un conjunto de herramientas de IA para el trabajo diario del docente. Le ayudamos a elegir según sus prioridades.'],
    ],
    relacionadas: ['aulamagica-ia', 'unticloud', 'bookstudio'],
    ld: { applicationSubCategory: 'Sistema de aprendizaje con inteligencia artificial', operatingSystem: 'Web' },
  },

  codexia: {
    titulo: 'Codexia: programación y pensamiento computacional en primaria',
    descripcion: 'Codexia enseña programación, lógica, matemáticas e IA a niños de 4 a 12 años con retos gamificados, editor de bloques y panel docente para colegios.',
    h1: 'Codexia: programación y pensamiento computacional para preescolar y primaria',
    altPortada: 'Página de inicio de Codexia, plataforma gamificada de programación para niños de 4 a 12 años',
    reto: [
      'Las familias valoran cada vez más que el colegio enseñe programación e inteligencia artificial desde los primeros años. Pero muchos colegios no cuentan con un currículo estructurado ni con docentes de primaria formados en programación.',
      'Además, los niños más pequeños aún no leen, cada estudiante avanza a un ritmo distinto y la coordinación necesita ver el progreso real de cada grupo, no solo la actividad.',
      'Codexia ofrece un programa completo y listo para usar: diez materias organizadas como mundos que se desbloquean, voz natural para quienes aún no leen, un paso progresivo de los bloques al código real y un panel para que el docente asigne y siga el avance.',
    ],
    nota: '<strong>Una ruta de programación completa.</strong> Codexia acompaña a los estudiantes de 4 a 12 años. Desde los 12, <a href="/soluciones/vcodepro/">VCodePro</a> continúa el camino con un editor profesional, inteligencia artificial y alineación con el Bachillerato Internacional. Si busca una opción centrada solo en programación, con voz en español en cada reto, conozca <a href="/soluciones/codenest-school/">CodeNest School</a>.',
    funciones: [
      ['bloques', 'Bloques y código real', 'Editor de bloques (Blockly) y editor de código (Monaco) con tres bandas de edad: íconos, mixto y código.'],
      ['capas', 'Diez materias', 'Programación, lógica, aritmética, geometría, informática, seguridad en internet, inteligencia artificial, física básica, preescolar y laboratorios.'],
      ['voz', 'Voz natural para preescolar', 'Cada instrucción se narra con voz natural, para que los niños de 4 a 6 años aprendan aunque aún no sepan leer.'],
      ['candado', 'Ejecución segura', 'El código del estudiante corre en un entorno aislado, con límites de tiempo y de instrucciones.'],
      ['usuarios', 'Panel docente', 'Grupos, sedes, asignaciones por estudiante o por aula y estadísticas de progreso en vivo.'],
      ['juego', 'Más de 200 juegos', 'Arcade, simuladores interactivos y plantillas de mini-juegos, con logros, estrellas y rachas que motivan la práctica.'],
    ],
    galeria: [],
    extra: {
      titulo: 'Pensado para el aula',
      items: [
        'Optimizado para tabletas escolares y computadores.',
        'Código de institución para inscribir a los estudiantes.',
        'Estadísticas de progreso por estudiante y por aula.',
        'Seguridad en internet y ciudadanía digital como materias propias.',
        'Primeros pasos en inteligencia artificial: datos, patrones y neuronas.',
        'Recompensas que motivan: estrellas, logros y avatar personalizable.',
      ],
    },
    publico: [
      ['birrete', 'Coordinación de primaria y preescolar', 'Un currículo estructurado desde los 4 años.', ['Materias que crecen en dificultad', 'Voz natural para prelectores', 'Asignaciones por aula']],
      ['codigo', 'Área de tecnología', 'Del bloque al código real.', ['Tres bandas de edad', 'Editor de código real', 'Ejecución en entorno aislado']],
      ['institucion', 'Rectoría', 'Un programa STEM que diferencia al colegio.', ['Programación e IA desde preescolar', 'Ruta continua con VCodePro', 'Progreso visible para las familias']],
      ['usuarios', 'Docentes', 'Seguimiento sin esfuerzo.', ['Grupos y asignaciones', 'Estadísticas en vivo', 'Reportes de avance']],
    ],
    implementacion: [
      ['Licencia de la institución', 'Se activa el plan Escuela anual para la institución completa.'],
      ['Inscribir estudiantes', 'Los estudiantes se inscriben con el código de la institución.'],
      ['Organizar grupos', 'Los docentes crean grupos y sedes y asignan actividades por estudiante o por aula.'],
      ['Seguir el progreso', 'El panel muestra en vivo el avance de cada estudiante y de cada grupo.'],
    ],
    licencias: {
      intro: 'Para colegios, Codexia ofrece una licencia anual para la institución completa.',
      modalidades: [
        ['Plan Escuela', 'Renovación anual para toda la institución.', ['Todas las materias y más de 200 juegos', 'Editores de bloques y de código real', 'Panel docente: grupos, sedes y asignaciones', 'Código de institución para inscribir estudiantes', 'Estadísticas de progreso en vivo', 'Soporte prioritario y acompañamiento']],
      ],
    },
    preguntas: [
      ['¿Desde qué edad se puede usar?', 'Desde los 4 años con la sección Preescolar, que usa voz natural e íconos grandes, hasta los 12 años con programación en código.'],
      ['¿Los niños necesitan saber leer?', 'No. En Preescolar cada instrucción se narra con voz natural, así que aprenden aunque aún no lean ni escriban.'],
      ['¿Funciona en tabletas?', 'Sí. Codexia está optimizada para tabletas escolares, además de computadores.'],
      ['¿Es seguro para los niños?', 'El código se ejecuta en un entorno aislado. El fabricante declara cumplir normas de protección de datos de menores, como la Ley 1581 en Colombia, con consentimiento de los tutores.'],
      ['¿Qué sigue después de los 12 años?', 'VCodePro continúa la ruta con un editor de código profesional, inteligencia artificial integrada y alineación con las electivas de tecnología del Bachillerato Internacional.'],
    ],
    relacionadas: ['codenest-school', 'vcodepro', 'bookstudio'],
    ld: { applicationSubCategory: 'Programación y pensamiento computacional', operatingSystem: 'Web' },
  },

  'codenest-school': {
    titulo: 'CodeNest School: programación para niños desde los 4 años',
    descripcion: 'CodeNest School enseña programación de 4 a 12 años con 30 mundos, 600 actividades y voz en español. Los más pequeños programan sin necesidad de leer.',
    h1: 'CodeNest School: programación para niños desde los cuatro años',
    altPortada: 'Página de inicio de CodeNest School, plataforma para aprender a programar jugando desde los cuatro años',
    reto: [
      'Enseñar programación en preescolar choca con un hecho simple: un niño de cuatro años no puede leer una instrucción ni escribir una contraseña. La mayoría de las plataformas presuponen ambas cosas.',
      'A eso se suma que el colegio necesita una progresión real hasta el final de la primaria, docentes que puedan asignar y seguir el trabajo de cada grupo, y un tratamiento cuidadoso de los datos de los menores.',
      'CodeNest School está construido alrededor de esas condiciones: cada reto se narra con voz humana en español, los más pequeños programan arrastrando flechas y, con la edad, pasan a bloques y después a JavaScript o Python reales.',
    ],
    nota: '<strong>¿CodeNest School o Codexia?</strong> Ambas enseñan programación de los 4 a los 12 años. CodeNest School se concentra en programar, en tres etapas que van de las flechas sin texto al código real, con voz en español en cada reto. <a href="/soluciones/codexia/">Codexia</a> amplía el alcance a diez materias —matemáticas, lógica, inteligencia artificial, física y más— con más de 200 juegos. Le ayudamos a elegir según el enfoque de su institución. Desde los 12 años, la ruta continúa con <a href="/soluciones/vcodepro/">VCodePro</a>.',
    funciones: [
      ['voz', 'Cada reto en voz alta', 'Las instrucciones están narradas por una voz humana en español y se repiten cuantas veces haga falta, sin penalización.'],
      ['bloques', 'Programar arrastrando fichas', 'Flechas grandes, pensadas para dedos pequeños: en los diez primeros mundos no hay una sola palabra escrita.'],
      ['capas', 'Piezas que aparecen poco a poco', 'Se empieza con cuatro flechas; bucles, condicionales y funciones llegan cuando el niño domina lo anterior.'],
      ['insignia', 'Tres estrellas por actividad', 'La primera por llegar, la segunda por recogerlo todo y la tercera por resolverlo con el programa más corto.'],
      ['objetivo', 'Fallar no castiga', 'Si el programa no funciona, el personaje choca de forma cómica y anima a intentarlo otra vez, sin mensajes de error en rojo.'],
      ['grafica', 'Seguimiento del progreso', 'Reporte por estudiante con su avance por mundo, el tiempo dedicado y las actividades donde se atasca.'],
    ],
    galeria: [
      ['codenest-school-demo', 'Actividad del primer mundo de CodeNest School: tablero con el personaje, una estrella y una bandera, y el programa armado con fichas de flechas', 'Una actividad del primer mundo', 'El estudiante arma su programa con flechas y lo ejecuta para llevar al personaje hasta la bandera.'],
    ],
    extra: {
      titulo: 'Tres formas de programar, una por edad',
      items: [
        'Exploradores (4 a 6 años): fichas de flechas, sin palabras escritas.',
        'Creadores (7 a 9 años): bloques, con el código generado a la vista.',
        'Hackers (10 a 12 años o más): JavaScript o Python en un editor real.',
        'Secuencias, condicionales, bucles, variables y funciones propias.',
        'Al final: algoritmos de búsqueda, ordenamiento y rutas.',
        'Funciona en el navegador, pensado para tableta y sin publicidad.',
      ],
    },
    publico: [
      ['birrete', 'Coordinación de preescolar y primaria', 'Programación desde los cuatro años.', ['Sin necesidad de saber leer', 'Progresión hasta los 12 años', 'Voz en español en cada reto']],
      ['codigo', 'Área de tecnología', 'Del juego al código real.', ['Flechas, bloques y después código', 'JavaScript o Python con editor real', 'Algoritmos y depuración']],
      ['usuarios', 'Docentes', 'Asignar y seguir sin esfuerzo.', ['Aulas con código de acceso', 'Mundos asignados con fecha límite', 'Matriz de seguimiento por grupo']],
      ['escudo', 'Coordinación TIC', 'Datos de menores protegidos.', ['Ingreso sin correo, con PIN de dibujos', 'Consentimiento del tutor registrado', 'Auditoría de accesos a datos de menores']],
    ],
    implementacion: [
      ['Licencia Escuela', 'Se activa el plan anual de la institución, con estudiantes y docentes ilimitados y varias sedes.'],
      ['Aulas y estudiantes', 'Cada aula recibe su código de acceso y la lista de estudiantes se carga de una sola vez.'],
      ['Asignación', 'Los docentes asignan mundos o actividades concretas a cada grupo, con fecha límite.'],
      ['Seguimiento', 'La matriz por estudiante y mundo muestra el avance y las actividades donde el grupo se atasca, para retomarlas en clase.'],
    ],
    licencias: {
      intro: 'Para colegios, CodeNest School ofrece una licencia anual que no se renueva automáticamente: al terminar el año, la institución decide si continúa.',
      modalidades: [
        ['Plan Escuela', 'Para colegios: sedes, docentes, aulas y seguimiento pedagógico completo.', ['Estudiantes y docentes ilimitados', 'Varias sedes y aulas con código de acceso', 'Alta masiva de estudiantes', 'Asignación de mundos y actividades por aula', 'Matriz de seguimiento y estadísticas por grupo', 'Capacitación inicial y soporte prioritario']],
      ],
    },
    preguntas: [
      ['¿Un niño de cuatro años puede usarlo sin saber leer?', 'Sí. En los diez primeros mundos no hay una sola palabra escrita: se programa arrastrando fichas de flechas y cada instrucción se narra con voz humana, que el niño puede volver a oír tocando el megáfono.'],
      ['¿Qué aprenden los estudiantes?', 'Secuencias y condicionales de los cuatro a los seis años; bucles, variables y funciones de los siete a los nueve, con bloques; y JavaScript o Python reales desde los diez, hasta algoritmos de rutas y manejo de errores.'],
      ['¿Hay que instalar algo?', 'No. Funciona en el navegador, en tableta y en computador, y está pensado para tabletas: botones grandes y juego táctil.'],
      ['¿Qué datos se guardan de los estudiantes?', 'Según el fabricante, los mínimos: los niños entran con un nombre de jugador y un PIN de cuatro dibujos, sin correo electrónico. Declara cumplir la Ley 1581 de 2012, registrar el consentimiento del tutor y auditar todo acceso a los datos de un menor, sin publicidad ni rastreadores de terceros.'],
      ['¿En qué se diferencia de Codexia?', 'CodeNest School se concentra en programación, con tres etapas por edad y voz en español en cada reto. Codexia abarca diez materias, entre ellas matemáticas, lógica, inteligencia artificial y física, con más de 200 juegos. Le ayudamos a elegir según el enfoque de su institución.'],
    ],
    relacionadas: ['codexia', 'vcodepro', 'bookstudio'],
    ld: { applicationSubCategory: 'Programación para niños', operatingSystem: 'Web' },
  },

  vcodepro: {
    titulo: 'VCodePro: programación e IA para bachillerato e IB · Grupo Logic',
    descripcion: 'VCodePro es un editor de código con IA y estudio de agentes para enseñar programación desde los 12 años, con rúbricas IB y bitácora de diseño MYP.',
    h1: 'VCodePro: programación e inteligencia artificial para bachillerato e IB',
    altPortada: 'Página de inicio de VCodePro con el editor de código con inteligencia artificial para el aula',
    reto: [
      'Sus estudiantes ya conviven con la inteligencia artificial. El reto del colegio es que dejen de ser usuarios pasivos y aprendan a construirla con criterio, sin que la IA haga el trabajo por ellos.',
      'Las asignaturas de tecnología del Bachillerato Internacional exigen además evidencias del proceso, evaluación por criterios y documentación del ciclo de diseño, una carga que suele recaer por completo en el docente.',
      'VCodePro lleva al aula un editor profesional con inteligencia artificial en modo pedagógico, un estudio para crear agentes de IA y las herramientas de evaluación del IB integradas, para que el docente enseñe y evalúe en un mismo lugar.',
    ],
    nota: '<strong>Una ruta de programación completa.</strong> VCodePro recibe a los estudiantes desde los 12 años. Para preescolar y primaria, <a href="/soluciones/codexia/">Codexia</a> y <a href="/soluciones/codenest-school/">CodeNest School</a> desarrollan el pensamiento computacional de los 4 a los 12 años.',
    funciones: [
      ['chispa', 'Asistente en modo pedagógico', 'La IA responde con preguntas, pistas y ejemplos análogos, no con soluciones. El docente decide cuánta ayuda recibe cada curso.'],
      ['robot', 'Estudio de agentes de IA', 'Los estudiantes definen el propósito de un agente, le asignan herramientas, lo prueban, miden su desempeño y lo publican para el curso.'],
      ['usuarios', 'Modo aula', 'El docente ve el avance de cada estudiante en tiempo real, comparte plantillas de proyecto y abre sesiones de programación en pareja.'],
      ['rubrica', 'Rúbricas IB integradas', 'Evaluación con los criterios A, B, C y D: el estudiante ve qué le falta antes de entregar y el docente exporta las notas.'],
      ['bitacora', 'Bitácora de diseño automática', 'Investigación, ideas, creación y evaluación del ciclo de diseño del MYP se registran a medida que el estudiante trabaja.'],
      ['interruptor', 'Integridad académica', 'Registro completo de conversaciones y versiones, filtros de contenido, topes de consumo y modo examen que desactiva la IA.'],
    ],
    galeria: [
      ['vcodepro-agentes', 'Estudio de agentes de VCodePro con un tutor de algoritmos que guía a un estudiante mediante preguntas', 'Estudio de agentes', 'Un agente creado en clase acompaña al estudiante con preguntas, sin entregar la solución.'],
    ],
    extra: {
      titulo: 'Lo que recibe su colegio',
      items: [
        'Plan de aula de 6.º a 12.º, con 32 sesiones por año.',
        'Banco de más de 120 proyectos y retos clasificados.',
        'Formación docente: cuatro talleres en vivo.',
        'Panel de coordinación con licencias, cursos y evidencias.',
        'Python, JavaScript, HTML, CSS, Java y C++.',
        'Windows, macOS y Linux; funciona en equipos modestos.',
      ],
    },
    publico: [
      ['codigo', 'Área de tecnología', 'Enseñar con herramientas de la industria.', ['Editor completo con depurador', 'Banco de proyectos', 'Plan de aula por nivel']],
      ['birrete', 'Coordinación IB', 'Alineado con las electivas de tecnología.', ['Informática NM y NS', 'Diseño y Diseño MYP', 'ITGS y Monografía']],
      ['ajustes', 'Coordinación TIC', 'Despliegue simple en las salas.', ['Instalación silenciosa', 'Control de lo que instala cada curso', 'Funciona sin conexión permanente']],
      ['institucion', 'Rectoría', 'Estudiantes que construyen la IA.', ['Agentes de IA en el aula', 'Integridad académica auditable', 'Ruta continua con Codexia']],
    ],
    implementacion: [
      ['Instalar', 'El editor se descarga para cada sistema operativo; en salas de cómputo puede desplegarse en todos los equipos a la vez.'],
      ['Activar la licencia', 'Con la clave institucional se habilitan el modo aula, las rúbricas y el panel de seguimiento.'],
      ['Crear cursos', 'Se importa la lista de estudiantes, se reparten las licencias y se comparte el primer proyecto con un código de clase.'],
      ['Enseñar y evaluar', 'Los estudiantes programan con pistas de la IA y el docente evalúa con los criterios del IB desde el mismo panel.'],
    ],
    licencias: {
      intro: 'El editor se descarga sin costo; la licencia habilita las funciones de aula, las rúbricas y el soporte. Hay tres modalidades.',
      modalidades: [
        ['Personal', 'Para el docente que prepara sus clases o el estudiante que practica en casa.', ['De 1 a 10 licencias individuales', 'Asistente de IA y estudio de agentes', 'Plantillas, rúbricas y banco de proyectos', 'Soporte por correo']],
        ['Escuela', 'Para el colegio que dicta las electivas de tecnología.', ['Hasta 100 licencias', 'IA de aula y agentes publicados por curso', 'Modo aula y panel docente', 'Rúbricas IB y exportación de notas', 'Formación para el equipo docente', 'Soporte prioritario']],
        ['Licencia de Sitio', 'Para programación en todos los niveles y todas las salas.', ['Hasta 500 licencias', 'Cuotas de IA por sede y modo examen', 'Despliegue asistido en las salas', 'Panel de coordinación académica', 'Acompañamiento pedagógico anual']],
      ],
      pie: '¿Más de 500 licencias o varias sedes? Preparamos un acuerdo a la medida.',
    },
    preguntas: [
      ['¿La IA hace las tareas por el estudiante?', 'No. En modo pedagógico el asistente responde con preguntas, pistas y ejemplos análogos. Además, el docente controla cuánta ayuda recibe cada curso y puede activar el modo examen, que desactiva la IA.'],
      ['¿Necesitamos computadores potentes?', 'No. El fabricante indica que VCodePro arranca en segundos, pesa poco y funciona en salas con computadores de varios años, sin conexión permanente.'],
      ['¿Solo sirve para colegios del Bachillerato Internacional?', 'No. Incluye un plan de aula de 6.º a 12.º útil para cualquier colegio; su diferencia es que está especialmente alineado con las electivas de tecnología del IB y con el ciclo de diseño del MYP.'],
      ['¿Qué lenguajes de programación soporta?', 'Python, JavaScript, HTML, CSS, Java y C++, con resaltado de sintaxis, autocompletado, depurador, terminal integrada y control de versiones.'],
      ['¿Cómo se relaciona con Codexia?', 'Son dos etapas de una misma ruta: Codexia desarrolla el pensamiento computacional de los 4 a los 12 años y VCodePro continúa desde los 12 con programación profesional e inteligencia artificial.'],
    ],
    relacionadas: ['codexia', 'veyon-control', 'unticloud'],
    ld: { applicationSubCategory: 'Editor de código educativo', operatingSystem: 'Windows, macOS, Linux', softwareVersion: '2.4' },
  },

  bookstudio: {
    titulo: 'BookStudio: libros interactivos para colegios · Grupo Logic',
    descripcion: 'BookStudio permite crear libros interactivos con voz, video, mapas, gráficas y preguntas autocorregibles, con valoraciones y seguimiento docente.',
    h1: 'BookStudio: libros interactivos creados por su comunidad educativa',
    altPortada: 'Página de inicio de BookStudio, plataforma de libros interactivos que el alumnado crea, escucha y comparte',
    reto: [
      'Los estudiantes aprenden más cuando producen: cuando explican con su propia voz, organizan ideas y comparten lo que crearon. Sin embargo, el trabajo escolar sigue atrapado en cuadernos y documentos estáticos que nadie más vuelve a leer.',
      'Para el docente, además, revisar, valorar y dar seguimiento a ese trabajo en varias herramientas distintas consume un tiempo que no tiene.',
      'BookStudio ofrece un lienzo donde caben texto, voz, video, mapas, gráficas y preguntas que se corrigen solas. El alumnado crea, escucha y comparte; el docente reparte material, valora con nota y comentario y sigue el trabajo real de cada estudiante.',
    ],
    funciones: [
      ['lapiz', 'Lienzo libre', 'Texto, imágenes, formas, íconos y dibujos donde tengan sentido: 26 formas, 2.048 íconos y 17 tipografías, incluida OpenDyslexic.'],
      ['microfono', 'Voz, foto y video', 'Se graban desde el navegador con la cámara y el micrófono del equipo y se insertan en la página.'],
      ['pregunta', 'Preguntas autocorregibles', 'Respuesta única, varias respuestas u ordenar, con texto e imágenes. La solución se comprueba en el servidor.'],
      ['grafica', 'Gráficas, fórmulas y mapas', 'Seis tipos de gráfica con datos editables, fórmulas en LaTeX y mapas de OpenStreetMap dentro del documento.'],
      ['rubrica', 'Valoraciones y seguimiento', 'Nota y comentario por libro, cuadrícula de la clase con el promedio de cada estudiante y bitácora del tiempo de trabajo real.'],
      ['exportar', 'Su contenido sale con usted', 'Exportación a PDF o a una página web autónoma de un solo archivo, que se abre sin la plataforma.'],
    ],
    galeria: [
      ['bookstudio-editor', 'Editor de BookStudio con herramientas para insertar texto, imagen, mapa, pregunta y gráfica, y una página con la plantilla de mapa del cuento', 'El editor', 'Captura de la versión de prueba: herramientas de inserción a la izquierda y una de sus 24 plantillas en el lienzo.'],
    ],
    extra: {
      titulo: 'Más funciones para el aula',
      items: [
        'Entrega de una página o un libro a toda la clase, con copia editable para cada estudiante.',
        'Bibliotecas con estudiantes de varios cursos, traídos del sistema académico.',
        'Libros colaborativos en los que toda la clase aporta contenido.',
        'Organizadores gráficos listos: Venn, KWL, mapa del cuento, espina de pescado.',
        'Medios con licencia Creative Commons y atribución automática.',
        'Enlaces de solo lectura, públicos o restringidos y revocables con un clic.',
      ],
    },
    publico: [
      ['birrete', 'Coordinación académica', 'Proyectos que dejan evidencia.', ['Portafolios y diarios de lectura', 'Organizadores gráficos listos', 'Accesibilidad de serie']],
      ['usuarios', 'Docentes', 'Valorar y seguir sin esfuerzo.', ['Reparto de material a la clase', 'Nota y comentario por libro', 'Bitácora de trabajo']],
      ['microfono', 'Estudiantes', 'Aprender creando.', ['Grabar su propia voz', 'Preguntas que dan ánimo al acertar', 'Ingreso con código QR']],
      ['ajustes', 'Coordinación TIC', 'Nada que instalar.', ['Funciona en el navegador', 'Importación de grupos', 'Integración con el directorio de usuarios']],
    ],
    implementacion: [
      ['Crear el libro', 'Se elige el formato y se empieza de cero o con una de las 24 plantillas.'],
      ['Llenar las páginas', 'Texto, imágenes, audio, gráficas o preguntas se arrastran al lienzo.'],
      ['Invitar al grupo', 'Con un enlace, un código QR o eligiendo estudiantes curso por curso.'],
      ['Valorar y publicar', 'El docente pone nota con su comentario, comparte el enlace o exporta a PDF.'],
    ],
    licencias: {
      intro: 'BookStudio se contrata por año, desde un docente hasta la institución completa.',
      modalidades: [
        ['Individual', 'Para un docente que trabaja por su cuenta.', ['Todas las funciones del editor', 'Libros y páginas ilimitados', 'Enlaces para compartir y modo lectura', 'Exportación a PDF y a página web']],
        ['Escuela', 'Hasta 5 profesores y 500 estudiantes.', ['Alojamiento, copias de seguridad y actualizaciones', 'Importación de grupos desde el sistema académico', 'Edición colaborativa por curso', 'Formación inicial para el profesorado', 'Soporte por correo']],
        ['Institucional', 'Usuarios ilimitados.', ['Dominio e imagen propios', 'Integración con su directorio de usuarios', 'Acuerdo de nivel de servicio', 'Soporte prioritario', 'Formación y acompañamiento continuo']],
      ],
      pie: 'El fabricante ofrece condiciones especiales para centros públicos y entidades sin ánimo de lucro. Consúltenos.',
    },
    preguntas: [
      ['¿Se puede probar antes de contratar?', 'Sí. El sitio oficial permite entrar al editor completo sin registrarse, con un límite de un libro de dos páginas. En la demostración le mostramos además las funciones para la clase.'],
      ['¿Qué necesita el alumnado para entrar?', 'Solo un navegador. Los más pequeños entran con un código QR, sin correo ni contraseña; el resto, con su correo institucional.'],
      ['¿Dónde se guardan los datos del alumnado?', 'Según el fabricante, en sus servidores, cifrados en tránsito y con copia de seguridad diaria, sin seguimiento publicitario ni cesión de datos a terceros.'],
      ['¿Podemos llevarnos los libros si dejamos de usar el servicio?', 'Sí. Cada libro se exporta a PDF o a una página web de un solo archivo, con sus imágenes y su navegación, que se abre con doble clic sin la plataforma.'],
      ['¿Varias personas pueden editar el mismo libro?', 'Sí. Un libro marcado como colaborativo recibe aportes de todo el grupo. Los cambios de otras personas aparecen al recargar la página.'],
    ],
    relacionadas: ['edunova', 'codexia', 'aulamagica-ia'],
    ld: { applicationSubCategory: 'Creación de libros interactivos', operatingSystem: 'Web' },
  },
};
