// Contenido de cada página de producto.
// Todos los productos son desarrollados y comercializados por Grupo Logic.
// Precios en pesos colombianos (COP), tomados del sitio de cada producto (octubre de 2026).
// Cada plan: { nombre, para, precio, periodo, items }. precio = null → se cotiza.

export const CONTENIDO = {
  unticloud: {
    titulo: 'UntiCloud: horarios y ausentismo docente desde Untis · Grupo Logic',
    descripcion: 'UntiCloud es el software web que lleva Untis a la nube: horarios en tiempo real, guardias, reemplazos e indicadores de ausentismo docente.',
    h1: 'UntiCloud: horarios, guardias y ausentismo docente de Untis, en la web',
    altPortada: 'Página de inicio de UntiCloud con el panel de administración de horarios, guardias y estadísticas',
    reto: [
      'Muchos colegios planifican sus horarios con Untis, pero la información queda encerrada en el equipo de escritorio de la coordinación. Los docentes dependen de horarios impresos, las sustituciones se coordinan por teléfono y rectoría no tiene a la mano el índice de ausentismo docente del mes.',
      'Calcular ese índice, verificar las horas de cada materia del programa IB o preparar el informe para la junta suele significar horas de trabajo manual en hojas de cálculo.',
      'UntiCloud resuelve el problema sin cambiar la forma de planificar: toma los mismos archivos que Untis Desktop ya exporta y los publica en un panel web, con la información que cada rol necesita.',
    ],
    funciones: [
      ['calendario', 'Horarios en tiempo real', 'Vistas por docente, por curso y en agenda semanal, actualizadas al instante y disponibles en cualquier dispositivo.'],
      ['grafica', 'Estadísticas de ausentismo', 'Índice de ausentismo docente por mes, motivo y curso, con filtro por sección. Se calcula solo sobre las horas que el docente debía impartir.'],
      ['escudo', 'Guardias de recreo', 'Cada docente ve qué día y en qué zona le corresponde vigilar. La asignación llega directamente desde Untis.'],
      ['reemplazo', 'Reemplazos y planificación', 'Sustituciones del día con PDF imprimible, disponibilidad docente para planificar ausencias e histórico por motivo.'],
      ['birrete', 'Indicadores IB', 'Cumplimiento de horas HL y SL frente a los mínimos del programa, seguimiento del núcleo EE·TdC·CAS y horas perdidas en la sección IB.'],
      ['comparar', 'Comparador y carga horaria', 'Compare en paralelo hasta 4 docentes o cursos y consulte la carga semanal de cada docente: lecciones, grupos, materias y salones.'],
    ],
    galeria: [
      ['unticloud-ib', 'Tabla de indicadores IB de UntiCloud con proyección de horas por materia frente al mínimo HL y SL', 'Indicadores IB', 'Semáforo de cumplimiento por materia y estado del núcleo IB, calculado a partir del horario de Untis.'],
      ['unticloud-ausentismo', 'Gráfica de UntiCloud con el índice de ausentismo docente por mes del año lectivo', 'Ausentismo por mes', 'Índice mensual con umbrales de atención para ver la tendencia del año lectivo de un vistazo.'],
    ],
    extra: {
      titulo: 'Integración directa con Untis',
      items: [
        'Compatible con Untis 2020 o superior.',
        'Lee los archivos GPU que Untis Desktop ya genera.',
        'Importación con un clic, sin duplicados y con historial de auditoría.',
        'Las secciones (IB, bachillerato, primaria…) se leen de Untis automáticamente.',
        'Usuarios y roles: cada perfil ve solo lo que necesita.',
        '100 % web: sin instalación ni servidores propios.',
      ],
    },
    publico: [
      ['institucion', 'Rectoría', 'Vista estratégica para decidir con datos.', ['Índice de ausentismo por período', 'Tendencias mes a mes', 'Horas sin cubrir con alerta visual']],
      ['ajustes', 'Coordinación TIC', 'Integración limpia con Untis.', ['Importación idempotente de archivos', 'Historial de importaciones con errores', 'Gestión de usuarios y permisos']],
      ['birrete', 'Coordinación académica e IB', 'Planificación y supervisión en un solo lugar.', ['Reemplazos del día y ausencias', 'Carga horaria por docente y curso', 'Semáforo HL/SL y núcleo IB']],
      ['usuarios', 'Docentes', 'Consulta rápida desde el celular.', ['Horario personal completo', 'Vigilancias y zonas asignadas', 'Sustituciones que le corresponden']],
    ],
    empezar: [
      ['Elija su plan', 'Institución, Profesional o Red de Colegios, según el tamaño de su colegio y los módulos que necesita.'],
      ['Active la licencia', 'Recibe el acceso al panel de administración de su institución.'],
      ['Importe desde Untis', 'Suba los archivos GPU que Untis Desktop ya exporta. La importación toma menos de 5 minutos.'],
      ['Abra el acceso', 'Configure los roles y docentes y directivos entran desde cualquier dispositivo.'],
    ],
    licencias: {
      intro: 'Licencia anual por institución. Incluye el uso del software, las actualizaciones y el soporte técnico durante la vigencia.',
      modalidades: [
        { nombre: 'Institución', para: 'Un centro educativo de hasta 150 docentes.', precio: '$11.200.000', periodo: 'COP / año', items: ['Horarios de docentes y cursos en tiempo real', 'Guardias y recreos', 'Estadísticas de ausentismo mensual', 'Sustituciones del día', 'Usuarios y roles'] },
        { nombre: 'Profesional', para: 'Para análisis avanzado y programa IB.', precio: '$15.000.000', periodo: 'COP / año', items: ['Todo lo del plan Institución', 'Módulo Indicadores IB', 'Filtro por sección en estadísticas', 'Planificación y carga horaria', 'Comparador de 4 horarios', 'Exportación PDF e informes para junta'] },
        { nombre: 'Red de Colegios', para: 'Varias sedes en un panel unificado.', precio: null, periodo: 'Precio según número de sedes', items: ['Todo lo del plan Profesional', 'Varias sedes en un panel', 'Estadísticas comparativas por sede', 'Acceso multi-institución por usuario', 'Nivel de servicio por contrato'] },
      ],
    },
    preguntas: [
      ['¿Tenemos que cambiar nuestra forma de planificar en Untis?', 'No. UntiCloud trabaja con los archivos GPU que Untis Desktop ya exporta. Su equipo sigue planificando exactamente igual.'],
      ['¿Qué versión de Untis necesitamos?', 'Untis 2020 o superior.'],
      ['¿Hay que instalar algo en los equipos del colegio?', 'No. UntiCloud funciona 100 % en la web, sin instalación ni servidores propios.'],
      ['¿El módulo de Indicadores IB está en todos los planes?', 'No. Indicadores IB se incluye en los planes Profesional y Red de Colegios.'],
      ['¿Cada usuario ve toda la información?', 'No. Cada rol ve solo lo que necesita: rectoría ve la información global, las coordinaciones sus herramientas de gestión y cada docente su propio horario y sus guardias.'],
    ],
    relacionadas: ['edunova', 'vcodepro', 'bookstudio'],
    ld: { applicationSubCategory: 'Gestión escolar y horarios', operatingSystem: 'Web' },
  },

  'aulamagica-ia': {
    titulo: 'AulaMágica IA: inteligencia artificial segura para colegios',
    descripcion: 'AulaMágica IA es una plataforma con más de 80 herramientas de IA para docentes y más de 50 para estudiantes, con control institucional de usuarios y uso.',
    h1: 'AulaMágica IA: inteligencia artificial segura para toda su institución',
    altPortada: 'Página de inicio de AulaMágica IA con su buscador de herramientas de inteligencia artificial para docentes',
    reto: [
      'Los docentes ya usan inteligencia artificial, muchas veces con cuentas personales y sin criterios comunes. La institución no sabe qué información se comparte, qué herramientas usan los estudiantes ni cómo se protege a los menores.',
      'Al mismo tiempo, el equipo docente dedica horas cada semana a planear, preparar evaluaciones, redactar observaciones de boletín y adaptar materiales para estudiantes con necesidades diversas.',
      'AulaMágica IA ordena ese uso bajo el control de la institución: una plataforma con herramientas pensadas para el aula, administración centralizada de usuarios y políticas de uso responsable que define cada colegio.',
    ],
    nota: '<strong>¿AulaMágica IA o EduNova?</strong> AulaMágica IA es un conjunto de herramientas de inteligencia artificial para el trabajo diario del docente y del estudiante. Si busca un sistema que conecte todo el ciclo de aprendizaje —libro de texto, clases, evaluación, recuperación y boletín—, vea <a href="/productos/edunova/">EduNova</a>.',
    funciones: [
      ['lapiz', 'Planeación de clases', 'Planes de clase alineados a estándares y DBA, presentaciones a partir de un tema o un texto, guías por pasos e ideas para actividades.'],
      ['rubrica', 'Evaluación', 'Quices de selección múltiple con clave de respuestas, rúbricas con niveles de desempeño y retroalimentación específica de los escritos.'],
      ['accesibilidad', 'Inclusión', 'Reescritor de textos por nivel de complejidad y apoyo para construir planes de ajustes razonables (PIAR) que el equipo revisa y aprueba.'],
      ['robot', 'Tutor para estudiantes', 'Un tutor de IA que guía sin dar la respuesta, dentro de actividades creadas y supervisadas por el docente.'],
      ['institucion', 'Administración institucional', 'Usuarios y licencias centralizados, paneles de uso y adopción por sede y políticas de uso responsable configurables.'],
      ['mensaje', 'Comunicación', 'Observaciones de boletín claras y respetuosas, y correos profesionales a familias y colegas con el tono adecuado.'],
    ],
    galeria: [],
    extra: {
      titulo: 'Seguridad e integraciones',
      items: [
        'Cifrado de la información en tránsito y en reposo.',
        'Control de acceso por roles e inicio de sesión con cuentas institucionales.',
        'Moderación de contenido y alertas para temas sensibles.',
        'Supervisión docente de las interacciones de los estudiantes.',
        'No usamos los datos de docentes ni estudiantes para entrenar modelos de IA.',
        'Integración con Google Workspace, Microsoft 365, Canvas, Moodle, Classroom y Teams.',
      ],
    },
    publico: [
      ['institucion', 'Rectoría', 'Visibilidad y control sobre el uso de la IA.', ['Paneles de uso y adopción por sede', 'Herramientas disponibles por perfil', 'Políticas de uso responsable']],
      ['ajustes', 'Coordinación TIC', 'Administración sin complicaciones.', ['Inicio de sesión institucional', 'Integración con Google y Microsoft', 'Alta de usuarios uno a uno o masiva']],
      ['birrete', 'Coordinación académica', 'Coherencia pedagógica en toda la institución.', ['Planes alineados a estándares y DBA', 'Observaciones con tono institucional', 'Apoyo a ajustes razonables']],
      ['usuarios', 'Docentes', 'Más tiempo para enseñar.', ['Más de 80 herramientas', 'Exportación a documentos y presentaciones', 'Tutor de IA para sus estudiantes']],
    ],
    empezar: [
      ['Elija su licencia', 'Escuela para una institución, o por Volumen para varias sedes o redes de colegios.'],
      ['Active la plataforma', 'Tras el pago, la licencia se activa y en el portal de clientes encuentra el código, los cupos y la vigencia.'],
      ['Configure su institución', 'Defina las políticas de uso y las herramientas disponibles para docentes y estudiantes.'],
      ['Invite a su equipo', 'Agregue docentes y directivos uno a uno o de forma masiva, y empiecen a usar las herramientas.'],
    ],
    licencias: {
      intro: 'Licencia por institución con vigencia de 12 meses. Incluye todas las herramientas, las actualizaciones, el soporte técnico y una capacitación inicial en línea.',
      modalidades: [
        { nombre: 'Licencia Escuela', para: 'Una institución, con una o varias jornadas.', precio: '$4.600.000', periodo: 'COP / 12 meses', items: ['Hasta 10 usuarios (docentes y directivos)', 'Más de 80 herramientas para docentes', 'Más de 50 herramientas para estudiantes', 'Panel de administración', 'Soporte técnico por correo y chat'] },
        { nombre: 'Licencia por Volumen', para: 'Redes de colegios, varias sedes y secretarías.', precio: '$10.000.000', periodo: 'COP / 12 meses', items: ['Hasta 250 usuarios en varias sedes', 'Todo lo de la Licencia Escuela', 'Herramientas personalizadas para su red', 'Reportes de uso e impacto por sede', 'Soporte técnico prioritario'] },
      ],
      pie: 'Más de 250 usuarios: precio por volumen.',
    },
    preguntas: [
      ['¿Los datos de docentes y estudiantes se usan para entrenar modelos de IA?', 'No. No usamos los datos de docentes ni estudiantes para entrenar modelos de IA ni vendemos información a terceros.'],
      ['¿Es seguro que los estudiantes usen la plataforma?', 'Los estudiantes trabajan en actividades creadas y supervisadas por el docente, con filtros de contenido adecuados a la edad, alertas para temas sensibles e historial visible para el docente en todo momento.'],
      ['¿Se integra con Google Workspace o Microsoft 365?', 'Sí. Permite iniciar sesión e integrarse con Google Workspace, Microsoft 365, Canvas, Moodle, Classroom y Teams.'],
      ['¿Podemos cambiar los usuarios durante la vigencia?', 'Sí. Desde el portal se pueden agregar, retirar o reemplazar usuarios en cualquier momento, dentro del número de cupos de la licencia.'],
      ['¿En qué se diferencia de EduNova?', 'AulaMágica IA es un conjunto de herramientas de IA para el trabajo diario del docente y del estudiante. EduNova es un sistema integrado que conecta libro de texto, clases, evaluación, recuperación y comunicación con las familias.'],
    ],
    relacionadas: ['edunova', 'bookstudio', 'vcodepro'],
    ld: { applicationSubCategory: 'Inteligencia artificial para la enseñanza', operatingSystem: 'Web' },
  },

  edunova: {
    titulo: 'EduNova: sistema de aprendizaje con IA para su colegio',
    descripcion: 'EduNova es una plataforma con IA de 8 módulos conectados, del libro de texto al boletín, para docentes, directivos, estudiantes y familias.',
    h1: 'EduNova: sistema de aprendizaje con IA para todo su colegio',
    altPortada: 'Página de inicio de EduNova con el módulo de planeación de clases con inteligencia artificial',
    reto: [
      'En muchos colegios, la planeación vive en un documento, las evaluaciones en otra plataforma, las notas en el sistema académico y la comunicación con las familias en grupos de mensajería. El trabajo se duplica y nadie tiene una visión completa del aprendizaje.',
      'Los directivos necesitan saber a tiempo qué grados, áreas o sedes requieren apoyo; los docentes, recuperar horas de planeación y corrección; y las familias, entender con claridad cómo avanzan sus hijos.',
      'EduNova reúne todo el ciclo en un solo sistema con inteligencia artificial: cada módulo alimenta al siguiente, desde el libro de texto hasta el boletín, y cada perfil de la comunidad educativa tiene su propio espacio.',
    ],
    nota: '<strong>¿EduNova o AulaMágica IA?</strong> EduNova es un sistema integrado para todo el ciclo de aprendizaje de la institución. Si lo que busca es un conjunto de herramientas de IA para el trabajo diario del docente, vea <a href="/productos/aulamagica-ia/">AulaMágica IA</a>.',
    funcionesTitulo: 'Ocho módulos conectados',
    funciones: [
      ['libro', '01 · Libros de texto', 'Contenidos por área, grado y periodo, alineados con los estándares básicos de competencias y los DBA.'],
      ['lapiz', '02 · Planeación', 'La IA propone objetivos, momentos de la clase, actividades y recursos. Todo es editable y se exporta a Word o PDF con el formato de su institución.'],
      ['presentacion', '03 · Clases', 'Presentaciones generadas desde la planeación, preguntas en vivo y tableros de participación. Funciona con conexión limitada.'],
      ['accesibilidad', '04 · Accesibilidad', 'Versión de lectura fácil, apoyos visuales, audio narrado y sugerencias de ajustes razonables según el PIAR.'],
      ['rubrica', '05 · Evaluaciones', 'Quices, talleres y simulacros con estructura de prueba de Estado, bancos de preguntas por competencia y rúbricas para preguntas abiertas.'],
      ['check', '06 · Calificación', 'Corrección asistida de respuestas abiertas y manuscritas, con retroalimentación personalizada que el docente revisa y aprueba.'],
      ['reemplazo', '07 · Recuperación', 'Identificación de aprendizajes por reforzar y actividades de nivelación a la medida de cada estudiante, con seguimiento del avance.'],
      ['familia', '08 · Comunicación', 'Boletines comprensibles, circulares programadas y resúmenes semanales para las familias.'],
    ],
    galeria: [
      ['edunova-libros', 'Biblioteca de EduNova con guías de Matemáticas, Ciencias Naturales, Lenguaje y Ciencias Sociales para grado quinto', 'Libros de texto', 'Guías organizadas por área, grado y unidad, alineadas a los DBA.'],
    ],
    extra: {
      titulo: 'EduNova Studio: libros digitales de su institución',
      items: [
        'Textos escolares propios con su modelo pedagógico y su PEI.',
        'Portadas, colores y logotipo de la institución.',
        'Libros digitales, listos también para imprimir.',
        'Contenido actualizable cada año.',
        'Incluido en la Licencia por Volumen.',
        'Funciona desde el navegador, sin instalación.',
      ],
    },
    publico: [
      ['institucion', 'Directivos', 'Visibilidad real del aprendizaje.', ['Indicadores por grado, área y sede', 'Alertas tempranas de bajo desempeño', 'Menos costo en materiales impresos']],
      ['lapiz', 'Docentes', 'Menos tareas repetitivas.', ['Planeaciones y guías con IA', 'Evaluaciones y rúbricas en segundos', 'Corrección asistida con retroalimentación']],
      ['birrete', 'Estudiantes', 'Un tutor que se adapta a su ritmo.', ['Tutor con IA que explica paso a paso', 'Retos y progreso visible', 'Práctica personalizada de refuerzo']],
      ['familia', 'Familias', 'Seguir el proceso escolar sin complicaciones.', ['Boletines claros', 'Avisos y circulares en el celular', 'Recomendaciones para apoyar en casa']],
    ],
    empezar: [
      ['Elija su licencia', 'Escuela para una institución con una sede, o por Volumen para varias sedes o redes de colegios.'],
      ['Active la plataforma', 'Tras el pago, la licencia se activa y el portal de clientes muestra el código, la vigencia y los cupos.'],
      ['Registre a su equipo', 'Agregue docentes y directivos desde el portal, también por carga masiva.'],
      ['Empiece a usarla', 'Planee, evalúe y comuníquese con las familias desde el navegador, sin instalar nada.'],
    ],
    licencias: {
      intro: 'Licencia anual por institución. Incluye todas las herramientas, las actualizaciones, el soporte técnico y una capacitación inicial en línea.',
      modalidades: [
        { nombre: 'Licencia Escuela', para: 'Una institución con una sede.', precio: '$4.500.000', periodo: 'COP / año', items: ['Planeación de clases y guías con IA', 'Generador de evaluaciones y rúbricas', 'Corrección asistida y reportes', 'Materiales accesibles e inclusivos', 'Soporte técnico por correo'] },
        { nombre: 'Licencia por Volumen', para: 'Redes de colegios y grupos con varias sedes.', precio: '$7.500.000', periodo: 'COP / año', items: ['Hasta 250 usuarios y hasta 5 sedes', 'Todo lo de la Licencia Escuela', 'Panel de indicadores para directivos', 'Studio: libros digitales propios', 'Plan de recuperación por estudiante', 'Soporte técnico prioritario'] },
      ],
    },
    preguntas: [
      ['¿Hay que instalar algo?', 'No. EduNova funciona desde el navegador en computadores, tabletas y celulares; solo se necesita conexión a internet.'],
      ['¿Qué es EduNova Studio?', 'Es el módulo para crear libros de texto digitales propios, con el modelo pedagógico, la identidad y el contexto de su institución. Está incluido en la Licencia por Volumen.'],
      ['¿Incluye preparación para pruebas de Estado?', 'Sí. El módulo de Evaluaciones permite crear simulacros con estructura de prueba de Estado, con bancos de preguntas por competencia y distintos niveles de dificultad.'],
      ['¿Cómo se tratan los datos de los estudiantes?', 'Conforme a la Ley 1581 de 2012. La institución es dueña de su información y puede solicitar su exportación o eliminación.'],
      ['¿En qué se diferencia de AulaMágica IA?', 'EduNova integra el ciclo completo de aprendizaje en ocho módulos conectados. AulaMágica IA es un conjunto de herramientas de IA para el trabajo diario del docente.'],
    ],
    relacionadas: ['aulamagica-ia', 'unticloud', 'bookstudio'],
    ld: { applicationSubCategory: 'Sistema de aprendizaje con inteligencia artificial', operatingSystem: 'Web' },
  },

  codexia: {
    titulo: 'Codexia: programación y pensamiento computacional en primaria',
    descripcion: 'Codexia es una plataforma gamificada que enseña programación, lógica, matemáticas e IA a niños de 4 a 12 años, con panel docente para colegios.',
    h1: 'Codexia: programación y pensamiento computacional para preescolar y primaria',
    altPortada: 'Página de inicio de Codexia, plataforma gamificada de programación para niños de 4 a 12 años',
    reto: [
      'Las familias valoran cada vez más que el colegio enseñe programación e inteligencia artificial desde los primeros años, pero muchos colegios no cuentan con un currículo estructurado para hacerlo.',
      'Además, los niños más pequeños aún no leen, cada estudiante avanza a un ritmo distinto y la coordinación necesita ver el progreso real de cada grupo.',
      'Codexia es un programa completo y listo para usar: diez materias organizadas como mundos que se desbloquean, voz natural para quienes aún no leen, un paso progresivo de los bloques al código real y un panel para que el docente asigne y siga el avance.',
    ],
    nota: '<strong>Una ruta de programación completa.</strong> Codexia cubre de los 4 a los 12 años. Desde los 12, <a href="/productos/vcodepro/">VCodePro</a> continúa con un editor profesional e inteligencia artificial. Si prefiere un producto centrado solo en programación, con voz en español en cada reto, vea <a href="/productos/codenest-school/">CodeNest School</a>.',
    funciones: [
      ['bloques', 'Bloques y código real', 'Editor de bloques (Blockly) y editor de código (Monaco) con tres bandas de edad: íconos, mixto y código.'],
      ['capas', 'Diez materias', 'Programación, lógica, aritmética, geometría, informática, seguridad en internet, inteligencia artificial, física básica, preescolar y laboratorios.'],
      ['voz', 'Voz natural para preescolar', 'Cada instrucción se narra con voz natural, para que los niños de 4 a 6 años aprendan aunque aún no sepan leer.'],
      ['candado', 'Ejecución segura', 'El código del estudiante corre en un entorno aislado, con límites de tiempo y de instrucciones.'],
      ['usuarios', 'Panel docente', 'Grupos, sedes, asignaciones por estudiante o por aula y estadísticas de progreso en vivo.'],
      ['juego', 'Más de 200 juegos', 'Arcade, simuladores interactivos y plantillas de mini-juegos, con logros, estrellas y rachas que motivan la práctica.'],
    ],
    galeria: [],
    extra: {
      titulo: 'Pensado para el aula',
      items: [
        'Optimizado para tabletas escolares y computadores.',
        'Código de institución para inscribir a los estudiantes.',
        'Estadísticas de progreso por estudiante y por aula.',
        'Seguridad en internet y ciudadanía digital como materias propias.',
        'Primeros pasos en inteligencia artificial: datos, patrones y neuronas.',
        'Recompensas que motivan: estrellas, logros y avatar personalizable.',
      ],
    },
    publico: [
      ['birrete', 'Coordinación de primaria y preescolar', 'Un currículo estructurado desde los 4 años.', ['Materias que crecen en dificultad', 'Voz natural para prelectores', 'Asignaciones por aula']],
      ['codigo', 'Área de tecnología', 'Del bloque al código real.', ['Tres bandas de edad', 'Editor de código real', 'Ejecución en entorno aislado']],
      ['institucion', 'Rectoría', 'Un programa STEM que diferencia al colegio.', ['Programación e IA desde preescolar', 'Ruta continua con VCodePro', 'Progreso visible para las familias']],
      ['usuarios', 'Docentes', 'Seguimiento sin esfuerzo.', ['Grupos y asignaciones', 'Estadísticas en vivo', 'Reportes de avance']],
    ],
    empezar: [
      ['Elija su plan', 'Escuela para toda la institución, o Individual para un estudiante. También hay una prueba de 24 horas.'],
      ['Active la licencia', 'La institución recibe su código para inscribir estudiantes.'],
      ['Organice los grupos', 'Los docentes crean grupos y sedes y asignan actividades por estudiante o por aula.'],
      ['Siga el progreso', 'El panel muestra en vivo el avance de cada estudiante y de cada grupo.'],
    ],
    licencias: {
      intro: 'Licencias anuales con acceso a todas las materias, actualizaciones incluidas y soporte técnico durante la vigencia.',
      modalidades: [
        { nombre: 'Prueba', para: 'Para conocer la plataforma.', precio: '$10.000', periodo: 'COP / 24 horas', items: ['Acceso completo a las 10 materias', 'Más de 200 juegos y laboratorios', 'Sin renovación automática'] },
        { nombre: 'Individual', para: 'Un estudiante, uso familiar.', precio: '$2.000.000', periodo: 'COP / año', items: ['Todas las materias y más de 200 juegos', 'Editores de bloques y de código real', 'Logros, avatares y progreso', 'Actualizaciones incluidas'] },
        { nombre: 'Escuela', para: 'Toda la institución.', precio: '$12.000.000', periodo: 'COP / año', items: ['Todo lo del plan Individual para sus estudiantes', 'Panel docente: grupos, sedes y asignaciones', 'Código de institución para inscribir estudiantes', 'Estadísticas de progreso en vivo', 'Soporte técnico prioritario'] },
      ],
    },
    preguntas: [
      ['¿Desde qué edad se puede usar?', 'Desde los 4 años con la sección Preescolar, que usa voz natural e íconos grandes, hasta los 12 años con programación en código.'],
      ['¿Los niños necesitan saber leer?', 'No. En Preescolar cada instrucción se narra con voz natural, así que aprenden aunque aún no lean ni escriban.'],
      ['¿Funciona en tabletas?', 'Sí. Codexia está optimizada para tabletas escolares, además de computadores.'],
      ['¿Es seguro para los niños?', 'El código se ejecuta en un entorno aislado y los datos de menores se tratan con consentimiento de los tutores, conforme a la Ley 1581 de 2012.'],
      ['¿Qué sigue después de los 12 años?', 'VCodePro continúa la ruta con un editor de código profesional e inteligencia artificial integrada.'],
    ],
    relacionadas: ['codenest-school', 'vcodepro', 'bookstudio'],
    ld: { applicationSubCategory: 'Programación y pensamiento computacional', operatingSystem: 'Web' },
  },

  'codenest-school': {
    titulo: 'CodeNest School: programación para niños desde los 4 años',
    descripcion: 'CodeNest School enseña programación de 4 a 12 años con 30 mundos, 600 actividades y voz en español. Los más pequeños programan sin necesidad de leer.',
    h1: 'CodeNest School: programación para niños desde los cuatro años',
    altPortada: 'Página de inicio de CodeNest School, plataforma para aprender a programar jugando desde los cuatro años',
    reto: [
      'Enseñar programación en preescolar choca con un hecho simple: un niño de cuatro años no puede leer una instrucción ni escribir una contraseña. La mayoría de las plataformas presuponen ambas cosas.',
      'A eso se suma que el colegio necesita una progresión real hasta el final de la primaria, docentes que puedan asignar y seguir el trabajo de cada grupo, y un tratamiento cuidadoso de los datos de los menores.',
      'CodeNest School está construido alrededor de esas condiciones: cada reto se narra con voz humana en español, los más pequeños programan arrastrando flechas y, con la edad, pasan a bloques y después a JavaScript o Python reales.',
    ],
    nota: '<strong>¿CodeNest School o Codexia?</strong> Ambos enseñan programación de los 4 a los 12 años. CodeNest School se concentra en programar, en tres etapas que van de las flechas sin texto al código real, con voz en español en cada reto. <a href="/productos/codexia/">Codexia</a> abarca diez materias —matemáticas, lógica, inteligencia artificial, física y más— con más de 200 juegos. Desde los 12 años, la ruta continúa con <a href="/productos/vcodepro/">VCodePro</a>.',
    funciones: [
      ['voz', 'Cada reto en voz alta', 'Las instrucciones están narradas por una voz humana en español y se repiten cuantas veces haga falta, sin penalización.'],
      ['bloques', 'Programar arrastrando fichas', 'Flechas grandes, pensadas para dedos pequeños: en los diez primeros mundos no hay una sola palabra escrita.'],
      ['capas', 'Piezas que aparecen poco a poco', 'Se empieza con cuatro flechas; bucles, condicionales y funciones llegan cuando el niño domina lo anterior.'],
      ['insignia', 'Tres estrellas por actividad', 'La primera por llegar, la segunda por recogerlo todo y la tercera por resolverlo con el programa más corto.'],
      ['objetivo', 'Fallar no castiga', 'Si el programa no funciona, el personaje choca de forma cómica y anima a intentarlo otra vez, sin mensajes de error en rojo.'],
      ['grafica', 'Seguimiento del progreso', 'Reporte por estudiante con su avance por mundo, el tiempo dedicado y las actividades donde se atasca.'],
    ],
    galeria: [
      ['codenest-school-demo', 'Actividad del primer mundo de CodeNest School: tablero con el personaje, una estrella y una bandera, y el programa armado con fichas de flechas', 'Una actividad del primer mundo', 'El estudiante arma su programa con flechas y lo ejecuta para llevar al personaje hasta la bandera.'],
    ],
    extra: {
      titulo: 'Tres formas de programar, una por edad',
      items: [
        'Exploradores (4 a 6 años): fichas de flechas, sin palabras escritas.',
        'Creadores (7 a 9 años): bloques, con el código generado a la vista.',
        'Hackers (10 a 12 años o más): JavaScript o Python en un editor real.',
        'Secuencias, condicionales, bucles, variables y funciones propias.',
        'Al final: algoritmos de búsqueda, ordenamiento y rutas.',
        'Funciona en el navegador, pensado para tableta y sin publicidad.',
      ],
    },
    publico: [
      ['birrete', 'Coordinación de preescolar y primaria', 'Programación desde los cuatro años.', ['Sin necesidad de saber leer', 'Progresión hasta los 12 años', 'Voz en español en cada reto']],
      ['codigo', 'Área de tecnología', 'Del juego al código real.', ['Flechas, bloques y después código', 'JavaScript o Python con editor real', 'Algoritmos y depuración']],
      ['usuarios', 'Docentes', 'Asignar y seguir sin esfuerzo.', ['Aulas con código de acceso', 'Mundos asignados con fecha límite', 'Matriz de seguimiento por grupo']],
      ['escudo', 'Coordinación TIC', 'Datos de menores protegidos.', ['Ingreso sin correo, con PIN de dibujos', 'Consentimiento del tutor registrado', 'Auditoría de accesos a datos de menores']],
    ],
    empezar: [
      ['Elija su plan', 'Escuela para colegios, o Personal y Padres para familias.'],
      ['Cree las aulas', 'Cada aula recibe su código de acceso y la lista de estudiantes se carga de una sola vez.'],
      ['Asigne actividades', 'Los docentes asignan mundos o actividades concretas a cada grupo, con fecha límite.'],
      ['Siga el avance', 'La matriz por estudiante y mundo muestra el progreso y dónde se atasca el grupo.'],
    ],
    licencias: {
      intro: 'Licencias anuales sin renovación automática: al terminar el año usted decide si continúa. Incluyen los 30 mundos, las 600 actividades, la voz en español y las actualizaciones.',
      modalidades: [
        { nombre: 'Personal', para: 'Un niño o niña que aprende en casa.', precio: '$180.000', periodo: 'COP / año', items: ['1 perfil con avatar personalizable', 'Los 30 mundos y las 600 actividades', 'Reporte de progreso para el tutor'] },
        { nombre: 'Padres', para: 'Familias con varios hijos.', precio: '$480.000', periodo: 'COP / año', items: ['Hasta 4 perfiles', 'Reportes comparativos por hijo', 'Control de tiempo de juego', 'Notificaciones de logros'] },
        { nombre: 'Escuela', para: 'Colegios: sedes, docentes y aulas.', precio: '$12.000.000', periodo: 'COP / año', items: ['Estudiantes y docentes ilimitados', 'Varias sedes y aulas con código de acceso', 'Alta masiva de estudiantes', 'Matriz de seguimiento por grupo', 'Auditoría de accesos (Ley 1581)', 'Soporte técnico prioritario'] },
      ],
    },
    preguntas: [
      ['¿Un niño de cuatro años puede usarlo sin saber leer?', 'Sí. En los diez primeros mundos no hay una sola palabra escrita: se programa arrastrando fichas de flechas y cada instrucción se narra con voz humana, que el niño puede volver a oír tocando el megáfono.'],
      ['¿Qué aprenden los estudiantes?', 'Secuencias y condicionales de los cuatro a los seis años; bucles, variables y funciones de los siete a los nueve, con bloques; y JavaScript o Python reales desde los diez, hasta algoritmos de rutas y manejo de errores.'],
      ['¿Hay que instalar algo?', 'No. Funciona en el navegador, en tableta y en computador, y está pensado para tabletas: botones grandes y juego táctil.'],
      ['¿Qué datos se guardan de los estudiantes?', 'Los mínimos: los niños entran con un nombre de jugador y un PIN de cuatro dibujos, sin correo electrónico. Registramos el consentimiento del tutor y auditamos todo acceso a los datos de un menor, conforme a la Ley 1581 de 2012, sin publicidad ni rastreadores de terceros.'],
      ['¿En qué se diferencia de Codexia?', 'CodeNest School se concentra en programación, con tres etapas por edad y voz en español en cada reto. Codexia abarca diez materias, entre ellas matemáticas, lógica, inteligencia artificial y física, con más de 200 juegos.'],
    ],
    relacionadas: ['codexia', 'vcodepro', 'bookstudio'],
    ld: { applicationSubCategory: 'Programación para niños', operatingSystem: 'Web' },
  },

  vcodepro: {
    titulo: 'VCodePro: programación e IA para bachillerato e IB · Grupo Logic',
    descripcion: 'VCodePro es un editor de código con IA y estudio de agentes para enseñar programación desde los 12 años, con rúbricas IB y bitácora de diseño MYP.',
    h1: 'VCodePro: programación e inteligencia artificial para bachillerato e IB',
    altPortada: 'Página de inicio de VCodePro con el editor de código con inteligencia artificial para el aula',
    reto: [
      'Los estudiantes ya conviven con la inteligencia artificial. El reto es que dejen de ser usuarios pasivos y aprendan a construirla con criterio, sin que la IA haga el trabajo por ellos.',
      'Las asignaturas de tecnología del Bachillerato Internacional exigen además evidencias del proceso, evaluación por criterios y documentación del ciclo de diseño, una carga que suele recaer en el docente.',
      'VCodePro es un editor profesional con inteligencia artificial en modo pedagógico, un estudio para crear agentes de IA y las herramientas de evaluación del IB integradas, para enseñar y evaluar en un mismo lugar.',
    ],
    nota: '<strong>Una ruta de programación completa.</strong> VCodePro recibe a los estudiantes desde los 12 años. Para preescolar y primaria, <a href="/productos/codexia/">Codexia</a> y <a href="/productos/codenest-school/">CodeNest School</a> desarrollan el pensamiento computacional de los 4 a los 12 años.',
    funciones: [
      ['chispa', 'Asistente en modo pedagógico', 'La IA responde con preguntas, pistas y ejemplos análogos, no con soluciones. El docente decide cuánta ayuda recibe cada curso.'],
      ['robot', 'Estudio de agentes de IA', 'Los estudiantes definen el propósito de un agente, le asignan herramientas, lo prueban, miden su desempeño y lo publican para el curso.'],
      ['usuarios', 'Modo aula', 'El docente ve el avance de cada estudiante en tiempo real, comparte plantillas de proyecto y abre sesiones de programación en pareja.'],
      ['rubrica', 'Rúbricas IB integradas', 'Evaluación con los criterios A, B, C y D: el estudiante ve qué le falta antes de entregar y el docente exporta las notas.'],
      ['bitacora', 'Bitácora de diseño automática', 'Investigación, ideas, creación y evaluación del ciclo de diseño del MYP se registran a medida que el estudiante trabaja.'],
      ['interruptor', 'Integridad académica', 'Registro completo de conversaciones y versiones, filtros de contenido, topes de consumo y modo examen que desactiva la IA.'],
    ],
    galeria: [
      ['vcodepro-agentes', 'Estudio de agentes de VCodePro con un tutor de algoritmos que guía a un estudiante mediante preguntas', 'Estudio de agentes', 'Un agente creado en clase guía al estudiante con preguntas, sin entregar la solución.'],
    ],
    extra: {
      titulo: 'Incluido con la licencia',
      items: [
        'Plan de aula de 6.º a 12.º, con 32 sesiones por año.',
        'Banco de más de 120 proyectos y retos clasificados.',
        'Panel de coordinación con licencias, cursos y evidencias.',
        'Python, JavaScript, HTML, CSS, Java y C++.',
        'Windows, macOS y Linux; funciona en equipos modestos.',
        'Actualizaciones de versión durante la vigencia.',
      ],
    },
    publico: [
      ['codigo', 'Área de tecnología', 'Enseñar con herramientas de la industria.', ['Editor completo con depurador', 'Banco de proyectos', 'Plan de aula por nivel']],
      ['birrete', 'Coordinación IB', 'Alineado con las electivas de tecnología.', ['Informática NM y NS', 'Diseño y Diseño MYP', 'ITGS y Monografía']],
      ['ajustes', 'Coordinación TIC', 'Despliegue simple en las salas.', ['Instalación silenciosa', 'Control de lo que instala cada curso', 'Funciona sin conexión permanente']],
      ['institucion', 'Rectoría', 'Estudiantes que construyen la IA.', ['Agentes de IA en el aula', 'Integridad académica auditable', 'Ruta continua desde primaria']],
    ],
    empezar: [
      ['Descargue el editor', 'Es gratuito para Windows, macOS y Linux; en salas de cómputo se despliega en todos los equipos a la vez.'],
      ['Active la licencia', 'La clave de licencia habilita el modo aula, las rúbricas y el panel de seguimiento.'],
      ['Cree sus cursos', 'Importe la lista de estudiantes, reparta las licencias y comparta el primer proyecto con un código de clase.'],
      ['Enseñe y evalúe', 'Los estudiantes programan con pistas de la IA y el docente evalúa con los criterios del IB desde el mismo panel.'],
    ],
    licencias: {
      intro: 'El editor se descarga sin costo; la licencia habilita las funciones de aula, las rúbricas, las actualizaciones y el soporte técnico.',
      modalidades: [
        { nombre: 'Personal', para: 'Un docente o un estudiante.', precio: '$150.000', periodo: 'COP / mes por licencia', items: ['De 1 a 10 licencias individuales', 'Asistente de IA y estudio de agentes', 'Plantillas, rúbricas y banco de proyectos', 'Sin permanencia mínima'] },
        { nombre: 'Escuela', para: 'Electivas de tecnología del colegio.', precio: '$5.000.000', periodo: 'COP / año · hasta 100 licencias', items: ['IA de aula y agentes publicados por curso', 'Modo aula y panel docente', 'Rúbricas IB y exportación de notas', 'Soporte técnico prioritario'] },
        { nombre: 'Licencia de Sitio', para: 'Todos los niveles y todas las salas.', precio: '$20.000.000', periodo: 'COP / año · hasta 500 licencias', items: ['Cuotas de IA por sede y modo examen', 'Instalación en todas las salas', 'Panel de coordinación académica', 'Soporte con tiempo de respuesta acordado'] },
      ],
      pie: 'Más de 500 licencias o varias sedes: precio por volumen.',
    },
    preguntas: [
      ['¿La IA hace las tareas por el estudiante?', 'No. En modo pedagógico el asistente responde con preguntas, pistas y ejemplos análogos. Además, el docente controla cuánta ayuda recibe cada curso y puede activar el modo examen, que desactiva la IA.'],
      ['¿Necesitamos computadores potentes?', 'No. VCodePro arranca en segundos, pesa poco y funciona en salas con computadores de varios años, sin conexión permanente.'],
      ['¿Solo sirve para colegios del Bachillerato Internacional?', 'No. Incluye un plan de aula de 6.º a 12.º útil para cualquier colegio; además está alineado con las electivas de tecnología del IB y con el ciclo de diseño del MYP.'],
      ['¿Qué lenguajes de programación soporta?', 'Python, JavaScript, HTML, CSS, Java y C++, con resaltado de sintaxis, autocompletado, depurador, terminal integrada y control de versiones.'],
      ['¿Puedo probarlo antes de comprar?', 'Sí. El editor se descarga gratis; la licencia habilita las funciones de aula y de evaluación.'],
    ],
    relacionadas: ['codexia', 'codenest-school', 'unticloud'],
    ld: { applicationSubCategory: 'Editor de código educativo', operatingSystem: 'Windows, macOS, Linux', softwareVersion: '2.4' },
  },

  bookstudio: {
    titulo: 'BookStudio: libros interactivos para colegios · Grupo Logic',
    descripcion: 'BookStudio es una plataforma web para crear libros interactivos con voz, video, mapas, gráficas y preguntas autocorregibles, con seguimiento docente.',
    h1: 'BookStudio: libros interactivos creados por su comunidad educativa',
    altPortada: 'Página de inicio de BookStudio, plataforma de libros interactivos que el alumnado crea, escucha y comparte',
    reto: [
      'Los estudiantes aprenden más cuando producen: cuando explican con su propia voz, organizan ideas y comparten lo que crearon. Sin embargo, el trabajo escolar sigue atrapado en cuadernos y documentos estáticos.',
      'Para el docente, además, revisar, valorar y dar seguimiento a ese trabajo en varias herramientas distintas consume un tiempo que no tiene.',
      'BookStudio ofrece un lienzo donde caben texto, voz, video, mapas, gráficas y preguntas que se corrigen solas. El alumnado crea, escucha y comparte; el docente reparte material, valora con nota y comentario y sigue el trabajo de cada estudiante.',
    ],
    funciones: [
      ['lapiz', 'Lienzo libre', 'Texto, imágenes, formas, íconos y dibujos donde tengan sentido: 26 formas, 2.048 íconos y 17 tipografías, incluida OpenDyslexic.'],
      ['microfono', 'Voz, foto y video', 'Se graban desde el navegador con la cámara y el micrófono del equipo y se insertan en la página.'],
      ['pregunta', 'Preguntas autocorregibles', 'Respuesta única, varias respuestas u ordenar, con texto e imágenes. La solución se comprueba en el servidor.'],
      ['grafica', 'Gráficas, fórmulas y mapas', 'Seis tipos de gráfica con datos editables, fórmulas en LaTeX y mapas de OpenStreetMap dentro del documento.'],
      ['rubrica', 'Valoraciones y seguimiento', 'Nota y comentario por libro, cuadrícula de la clase con el promedio de cada estudiante y bitácora del tiempo de trabajo real.'],
      ['exportar', 'Su contenido sale con usted', 'Exportación a PDF o a una página web autónoma de un solo archivo, que se abre sin la plataforma.'],
    ],
    galeria: [
      ['bookstudio-editor', 'Editor de BookStudio con herramientas para insertar texto, imagen, mapa, pregunta y gráfica, y una página con la plantilla de mapa del cuento', 'El editor', 'Herramientas de inserción a la izquierda y una de las 24 plantillas en el lienzo.'],
    ],
    extra: {
      titulo: 'Más funciones para el aula',
      items: [
        'Entrega de una página o un libro a toda la clase, con copia editable para cada estudiante.',
        'Bibliotecas con estudiantes de varios cursos, traídos del sistema académico.',
        'Libros colaborativos en los que toda la clase aporta contenido.',
        'Organizadores gráficos listos: Venn, KWL, mapa del cuento, espina de pescado.',
        'Medios con licencia Creative Commons y atribución automática.',
        'Enlaces de solo lectura, públicos o restringidos y revocables con un clic.',
      ],
    },
    publico: [
      ['birrete', 'Coordinación académica', 'Proyectos que dejan evidencia.', ['Portafolios y diarios de lectura', 'Organizadores gráficos listos', 'Accesibilidad de serie']],
      ['usuarios', 'Docentes', 'Valorar y seguir sin esfuerzo.', ['Reparto de material a la clase', 'Nota y comentario por libro', 'Bitácora de trabajo']],
      ['microfono', 'Estudiantes', 'Aprender creando.', ['Grabar su propia voz', 'Preguntas que dan ánimo al acertar', 'Ingreso con código QR']],
      ['ajustes', 'Coordinación TIC', 'Nada que instalar.', ['Funciona en el navegador', 'Importación de grupos', 'Integración con el directorio de usuarios']],
    ],
    empezar: [
      ['Pruébelo gratis', 'Entre al editor sin registrarse, con un límite de un libro de dos páginas.'],
      ['Elija su plan', 'Individual, Escuela o Institucional, y active su cuenta.'],
      ['Invite a su grupo', 'Con un enlace, un código QR o eligiendo estudiantes curso por curso.'],
      ['Valore y publique', 'Ponga nota con su comentario, comparta el enlace o exporte a PDF.'],
    ],
    licencias: {
      intro: 'Licencias anuales, desde un docente hasta la institución completa. Incluyen alojamiento, copias de seguridad, actualizaciones y soporte técnico.',
      modalidades: [
        { nombre: 'Individual', para: 'Un docente.', precio: '$500.000', periodo: 'COP / año', items: ['Todas las funciones del editor', 'Libros y páginas ilimitados', 'Enlaces para compartir y modo lectura', 'Exportación a PDF y a página web'] },
        { nombre: 'Escuela', para: 'Hasta 5 profesores y 500 estudiantes.', precio: '$8.000.000', periodo: 'COP / año', items: ['Importación de grupos desde el sistema académico', 'Edición colaborativa por curso', 'Capacitación inicial en línea incluida', 'Soporte técnico por correo'] },
        { nombre: 'Institucional', para: 'Usuarios ilimitados.', precio: '$20.000.000', periodo: 'COP / año', items: ['Dominio e imagen propios', 'Integración con su directorio de usuarios', 'Acuerdo de nivel de servicio', 'Soporte técnico prioritario'] },
      ],
    },
    preguntas: [
      ['¿Se puede probar antes de comprar?', 'Sí. Puede entrar al editor completo sin registrarse, con un límite de un libro de dos páginas.'],
      ['¿Qué necesita el alumnado para entrar?', 'Solo un navegador. Los más pequeños entran con un código QR, sin correo ni contraseña; el resto, con su correo institucional.'],
      ['¿Dónde se guardan los datos del alumnado?', 'En nuestros servidores, cifrados en tránsito y con copia de seguridad diaria, sin seguimiento publicitario ni cesión de datos a terceros.'],
      ['¿Podemos llevarnos los libros si dejamos de usar el servicio?', 'Sí. Cada libro se exporta a PDF o a una página web de un solo archivo, con sus imágenes y su navegación, que se abre con doble clic sin la plataforma.'],
      ['¿Varias personas pueden editar el mismo libro?', 'Sí. Un libro marcado como colaborativo recibe aportes de todo el grupo. Los cambios de otras personas aparecen al recargar la página.'],
    ],
    relacionadas: ['edunova', 'aulamagica-ia', 'codenest-school'],
    ld: { applicationSubCategory: 'Creación de libros interactivos', operatingSystem: 'Web' },
  },
};
